package com.company.core.mapper;

import com.company.core.entity.UcUserInfoDo;
import com.company.core.entity.UcUserInfoDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AccountUserSelfDefineMapper {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    int countByExample(UcUserInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(UcUserInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    int insert(UcUserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    int insertSelective(UcUserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    List<UcUserInfoDo> selectByExample(UcUserInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    UcUserInfoDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UcUserInfoDo record, @Param("example") UcUserInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UcUserInfoDo record, @Param("example") UcUserInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UcUserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_USER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UcUserInfoDo record);
}