package com.company.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.company.core.entity.TblBTSSysUsrRoleDO;
import com.company.core.entity.TblBTSSysUsrRoleDOExample;
import com.company.core.entity.TblBTSSysUsrRoleDOKey;

public interface TblBTSSysUsrRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int countByExample(TblBTSSysUsrRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int deleteByExample(TblBTSSysUsrRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TblBTSSysUsrRoleDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int insert(TblBTSSysUsrRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int insertSelective(TblBTSSysUsrRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    List<TblBTSSysUsrRoleDO> selectByExample(TblBTSSysUsrRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    TblBTSSysUsrRoleDO selectByPrimaryKey(TblBTSSysUsrRoleDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblBTSSysUsrRoleDO record,
                                 @Param("example") TblBTSSysUsrRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblBTSSysUsrRoleDO record,
                        @Param("example") TblBTSSysUsrRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblBTSSysUsrRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_USR_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblBTSSysUsrRoleDO record);
}