package com.company.core.mapper;

import com.company.core.entity.TblBtsUsrMapDo;
import com.company.core.entity.TblBtsUsrMapDoExample;
import com.company.core.entity.TblBtsUsrMapDoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblBtsUsrMapDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    long countByExample(TblBtsUsrMapDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    int deleteByExample(TblBtsUsrMapDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TblBtsUsrMapDoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    int insert(TblBtsUsrMapDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    int insertSelective(TblBtsUsrMapDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    List<TblBtsUsrMapDo> selectByExample(TblBtsUsrMapDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    TblBtsUsrMapDo selectByPrimaryKey(TblBtsUsrMapDoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TblBtsUsrMapDo record, @Param("example") TblBtsUsrMapDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TblBtsUsrMapDo record, @Param("example") TblBtsUsrMapDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TblBtsUsrMapDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_USR_MAP
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TblBtsUsrMapDo record);
}