package com.company.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.company.core.entity.TblBTSSysRoleDO;
import com.company.core.entity.TblBTSSysRoleDOExample;

public interface TblBTSSysRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int countByExample(TblBTSSysRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int deleteByExample(TblBTSSysRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int insert(TblBTSSysRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int insertSelective(TblBTSSysRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    List<TblBTSSysRoleDO> selectByExample(TblBTSSysRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    TblBTSSysRoleDO selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblBTSSysRoleDO record,
                                 @Param("example") TblBTSSysRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblBTSSysRoleDO record,
                        @Param("example") TblBTSSysRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblBTSSysRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BTS_SYS_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblBTSSysRoleDO record);
}