package com.company.core.mapper;

import com.company.core.entity.UcAgentLevelDo;
import com.company.core.entity.UcAgentLevelDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcAgentLevelDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    long countByExample(UcAgentLevelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    int deleteByExample(UcAgentLevelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String agentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    int insert(UcAgentLevelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    int insertSelective(UcAgentLevelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    List<UcAgentLevelDo> selectByExample(UcAgentLevelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    UcAgentLevelDo selectByPrimaryKey(String agentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UcAgentLevelDo record, @Param("example") UcAgentLevelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UcAgentLevelDo record, @Param("example") UcAgentLevelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UcAgentLevelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_LEVEL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UcAgentLevelDo record);
}