package com.company.core.mapper;

import com.company.core.entity.UcAgentUserRelDo;
import com.company.core.entity.UcAgentUserRelDoExample;
import com.company.core.entity.UcAgentUserRelDoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcAgentUserRelDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    int countByExample(UcAgentUserRelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    int deleteByExample(UcAgentUserRelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UcAgentUserRelDoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    int insert(UcAgentUserRelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    int insertSelective(UcAgentUserRelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    List<UcAgentUserRelDo> selectByExample(UcAgentUserRelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    UcAgentUserRelDo selectByPrimaryKey(UcAgentUserRelDoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UcAgentUserRelDo record, @Param("example") UcAgentUserRelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UcAgentUserRelDo record, @Param("example") UcAgentUserRelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UcAgentUserRelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_AGENT_USER_REL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UcAgentUserRelDo record);
}