package com.company.core.mapper;

import com.company.core.entity.UcInstParamsDo;
import com.company.core.entity.UcInstParamsDoExample;
import com.company.core.entity.UcInstParamsDoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcInstParamsDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    int countByExample(UcInstParamsDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    int deleteByExample(UcInstParamsDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UcInstParamsDoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    int insert(UcInstParamsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    int insertSelective(UcInstParamsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    List<UcInstParamsDo> selectByExample(UcInstParamsDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    UcInstParamsDo selectByPrimaryKey(UcInstParamsDoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UcInstParamsDo record, @Param("example") UcInstParamsDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UcInstParamsDo record, @Param("example") UcInstParamsDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UcInstParamsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_INST_PARAMS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UcInstParamsDo record);
}