package com.company.core.mapper;

import com.company.core.entity.UcProdDo;
import com.company.core.entity.UcProdDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcProdDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    long countByExample(UcProdDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    int deleteByExample(UcProdDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    int insert(UcProdDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    int insertSelective(UcProdDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    List<UcProdDo> selectByExample(UcProdDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    UcProdDo selectByPrimaryKey(String prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UcProdDo record, @Param("example") UcProdDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UcProdDo record, @Param("example") UcProdDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UcProdDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UC_PROD
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UcProdDo record);
}