package com.company.core.mapper;

import com.company.core.entity.WzInfoDo;
import com.company.core.entity.WzInfoDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WzInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    long countByExample(WzInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    int deleteByExample(WzInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    int insert(WzInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    int insertSelective(WzInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    List<WzInfoDo> selectByExample(WzInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    WzInfoDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WzInfoDo record, @Param("example") WzInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WzInfoDo record, @Param("example") WzInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WzInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WzInfoDo record);
}