package com.company.core.entity;

public class AccountUserDo {
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.LOGIN_ID
     *
     * @mbggenerated
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.NICK_NAME
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.LOGIN_PASSWORD
     *
     * @mbggenerated
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.PAY_PASSWORD
     *
     * @mbggenerated
     */
    private String payPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.HAND_PASSWORD
     *
     * @mbggenerated
     */
    private String handPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.SALT
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.USER_TYPE
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.USER_STATUS
     *
     * @mbggenerated
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.USER_REG_SOURCE
     *
     * @mbggenerated
     */
    private String userRegSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.USER_REG_DEVICE_ID
     *
     * @mbggenerated
     */
    private String userRegDeviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.USER_PROMOTE_SOURCE
     *
     * @mbggenerated
     */
    private String userPromoteSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    private String modifySource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.MODIFY_USER
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.USER_RESV1
     *
     * @mbggenerated
     */
    private String userResv1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.USER_RESV2
     *
     * @mbggenerated
     */
    private String userResv2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.USER_RESV3
     *
     * @mbggenerated
     */
    private String userResv3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.LOCK_VERISON
     *
     * @mbggenerated
     */
    private String lockVerison;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.ID
     *
     * @return the value of UC_USER_INFO.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.ID
     *
     * @param id the value for UC_USER_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.MOBILE
     *
     * @return the value of UC_USER_INFO.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.MOBILE
     *
     * @param mobile the value for UC_USER_INFO.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.LOGIN_ID
     *
     * @return the value of UC_USER_INFO.LOGIN_ID
     *
     * @mbggenerated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.LOGIN_ID
     *
     * @param loginId the value for UC_USER_INFO.LOGIN_ID
     *
     * @mbggenerated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.USER_NAME
     *
     * @return the value of UC_USER_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.USER_NAME
     *
     * @param userName the value for UC_USER_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.NICK_NAME
     *
     * @return the value of UC_USER_INFO.NICK_NAME
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.NICK_NAME
     *
     * @param nickName the value for UC_USER_INFO.NICK_NAME
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.LOGIN_PASSWORD
     *
     * @return the value of UC_USER_INFO.LOGIN_PASSWORD
     *
     * @mbggenerated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.LOGIN_PASSWORD
     *
     * @param loginPassword the value for UC_USER_INFO.LOGIN_PASSWORD
     *
     * @mbggenerated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.PAY_PASSWORD
     *
     * @return the value of UC_USER_INFO.PAY_PASSWORD
     *
     * @mbggenerated
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.PAY_PASSWORD
     *
     * @param payPassword the value for UC_USER_INFO.PAY_PASSWORD
     *
     * @mbggenerated
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.HAND_PASSWORD
     *
     * @return the value of UC_USER_INFO.HAND_PASSWORD
     *
     * @mbggenerated
     */
    public String getHandPassword() {
        return handPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.HAND_PASSWORD
     *
     * @param handPassword the value for UC_USER_INFO.HAND_PASSWORD
     *
     * @mbggenerated
     */
    public void setHandPassword(String handPassword) {
        this.handPassword = handPassword == null ? null : handPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.SALT
     *
     * @return the value of UC_USER_INFO.SALT
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.SALT
     *
     * @param salt the value for UC_USER_INFO.SALT
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.USER_TYPE
     *
     * @return the value of UC_USER_INFO.USER_TYPE
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.USER_TYPE
     *
     * @param userType the value for UC_USER_INFO.USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.USER_STATUS
     *
     * @return the value of UC_USER_INFO.USER_STATUS
     *
     * @mbggenerated
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.USER_STATUS
     *
     * @param userStatus the value for UC_USER_INFO.USER_STATUS
     *
     * @mbggenerated
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.USER_REG_SOURCE
     *
     * @return the value of UC_USER_INFO.USER_REG_SOURCE
     *
     * @mbggenerated
     */
    public String getUserRegSource() {
        return userRegSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.USER_REG_SOURCE
     *
     * @param userRegSource the value for UC_USER_INFO.USER_REG_SOURCE
     *
     * @mbggenerated
     */
    public void setUserRegSource(String userRegSource) {
        this.userRegSource = userRegSource == null ? null : userRegSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.USER_REG_DEVICE_ID
     *
     * @return the value of UC_USER_INFO.USER_REG_DEVICE_ID
     *
     * @mbggenerated
     */
    public String getUserRegDeviceId() {
        return userRegDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.USER_REG_DEVICE_ID
     *
     * @param userRegDeviceId the value for UC_USER_INFO.USER_REG_DEVICE_ID
     *
     * @mbggenerated
     */
    public void setUserRegDeviceId(String userRegDeviceId) {
        this.userRegDeviceId = userRegDeviceId == null ? null : userRegDeviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.USER_PROMOTE_SOURCE
     *
     * @return the value of UC_USER_INFO.USER_PROMOTE_SOURCE
     *
     * @mbggenerated
     */
    public String getUserPromoteSource() {
        return userPromoteSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.USER_PROMOTE_SOURCE
     *
     * @param userPromoteSource the value for UC_USER_INFO.USER_PROMOTE_SOURCE
     *
     * @mbggenerated
     */
    public void setUserPromoteSource(String userPromoteSource) {
        this.userPromoteSource = userPromoteSource == null ? null : userPromoteSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.MODIFY_SOURCE
     *
     * @return the value of UC_USER_INFO.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    public String getModifySource() {
        return modifySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.MODIFY_SOURCE
     *
     * @param modifySource the value for UC_USER_INFO.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    public void setModifySource(String modifySource) {
        this.modifySource = modifySource == null ? null : modifySource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.MODIFY_USER
     *
     * @return the value of UC_USER_INFO.MODIFY_USER
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.MODIFY_USER
     *
     * @param modifyUser the value for UC_USER_INFO.MODIFY_USER
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.USER_RESV1
     *
     * @return the value of UC_USER_INFO.USER_RESV1
     *
     * @mbggenerated
     */
    public String getUserResv1() {
        return userResv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.USER_RESV1
     *
     * @param userResv1 the value for UC_USER_INFO.USER_RESV1
     *
     * @mbggenerated
     */
    public void setUserResv1(String userResv1) {
        this.userResv1 = userResv1 == null ? null : userResv1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.USER_RESV2
     *
     * @return the value of UC_USER_INFO.USER_RESV2
     *
     * @mbggenerated
     */
    public String getUserResv2() {
        return userResv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.USER_RESV2
     *
     * @param userResv2 the value for UC_USER_INFO.USER_RESV2
     *
     * @mbggenerated
     */
    public void setUserResv2(String userResv2) {
        this.userResv2 = userResv2 == null ? null : userResv2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.USER_RESV3
     *
     * @return the value of UC_USER_INFO.USER_RESV3
     *
     * @mbggenerated
     */
    public String getUserResv3() {
        return userResv3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.USER_RESV3
     *
     * @param userResv3 the value for UC_USER_INFO.USER_RESV3
     *
     * @mbggenerated
     */
    public void setUserResv3(String userResv3) {
        this.userResv3 = userResv3 == null ? null : userResv3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.LOCK_VERISON
     *
     * @return the value of UC_USER_INFO.LOCK_VERISON
     *
     * @mbggenerated
     */
    public String getLockVerison() {
        return lockVerison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.LOCK_VERISON
     *
     * @param lockVerison the value for UC_USER_INFO.LOCK_VERISON
     *
     * @mbggenerated
     */
    public void setLockVerison(String lockVerison) {
        this.lockVerison = lockVerison == null ? null : lockVerison.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.CREATE_TIME
     *
     * @return the value of UC_USER_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.CREATE_TIME
     *
     * @param createTime the value for UC_USER_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_INFO.UPDATE_TIME
     *
     * @return the value of UC_USER_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_INFO.UPDATE_TIME
     *
     * @param updateTime the value for UC_USER_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}