package com.company.core.entity;

public class QrcPaymentRecordDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.INST_ID
     *
     * @mbg.generated
     */
    private String instId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.MID
     *
     * @mbg.generated
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.TID
     *
     * @mbg.generated
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.ORDER_ID
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.ORDER_DATE
     *
     * @mbg.generated
     */
    private String orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.ORDER_TIME
     *
     * @mbg.generated
     */
    private String orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.ORDER_TYPE
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.PLATFORM_SEQ
     *
     * @mbg.generated
     */
    private String platformSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.QRC_CHANNEL
     *
     * @mbg.generated
     */
    private String qrcChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.QRC_CHANNEL_FLAG
     *
     * @mbg.generated
     */
    private String qrcChannelFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.QRC_CHANNEL_MID
     *
     * @mbg.generated
     */
    private String qrcChannelMid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.QRC_CHANNEL_TID
     *
     * @mbg.generated
     */
    private String qrcChannelTid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.QRC_PAYMENT_STATUS
     *
     * @mbg.generated
     */
    private String qrcPaymentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.CARD_NO
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.VIRTUAL_ACCT_NO
     *
     * @mbg.generated
     */
    private String virtualAcctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.TRADE_AMOUNT
     *
     * @mbg.generated
     */
    private String tradeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.FEE_AMOUNT
     *
     * @mbg.generated
     */
    private String feeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.NET_AMOUNT
     *
     * @mbg.generated
     */
    private String netAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BENIFIT_AMOUNT
     *
     * @mbg.generated
     */
    private String benifitAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.CREDIT_DEBIT_FLAG
     *
     * @mbg.generated
     */
    private String creditDebitFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_SEND_MODE
     *
     * @mbg.generated
     */
    private String bipiSendMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_SEND_ID
     *
     * @mbg.generated
     */
    private String bipiSendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_SEND_DATE
     *
     * @mbg.generated
     */
    private String bipiSendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_SEND_TIME
     *
     * @mbg.generated
     */
    private String bipiSendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_STATUS
     *
     * @mbg.generated
     */
    private String bipiStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_RESP_CODE
     *
     * @mbg.generated
     */
    private String bipiRespCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_RESP_MESSAGE
     *
     * @mbg.generated
     */
    private String bipiRespMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_TRACE_ID
     *
     * @mbg.generated
     */
    private String bipiTraceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_RESP_DATE
     *
     * @mbg.generated
     */
    private String bipiRespDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_RESP_TIME
     *
     * @mbg.generated
     */
    private String bipiRespTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_RESP_RESV1
     *
     * @mbg.generated
     */
    private String bipiRespResv1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.BIPI_RESP_RESV2
     *
     * @mbg.generated
     */
    private String bipiRespResv2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.CHECK_FLAG
     *
     * @mbg.generated
     */
    private String checkFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.CLEAR_DATE
     *
     * @mbg.generated
     */
    private String clearDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.PRINT_FLAG
     *
     * @mbg.generated
     */
    private String printFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.PAYMENT_RESV1
     *
     * @mbg.generated
     */
    private String paymentResv1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.PAYMENT_RESV2
     *
     * @mbg.generated
     */
    private String paymentResv2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.PAYMENT_RESV3
     *
     * @mbg.generated
     */
    private String paymentResv3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRC_PAYMENT_RECORD.CANCEL_OR_REFUND
     *
     * @mbg.generated
     */
    private String cancelOrRefund;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.ID
     *
     * @return the value of QRC_PAYMENT_RECORD.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.ID
     *
     * @param id the value for QRC_PAYMENT_RECORD.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.INST_ID
     *
     * @return the value of QRC_PAYMENT_RECORD.INST_ID
     *
     * @mbg.generated
     */
    public String getInstId() {
        return instId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.INST_ID
     *
     * @param instId the value for QRC_PAYMENT_RECORD.INST_ID
     *
     * @mbg.generated
     */
    public void setInstId(String instId) {
        this.instId = instId == null ? null : instId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.MID
     *
     * @return the value of QRC_PAYMENT_RECORD.MID
     *
     * @mbg.generated
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.MID
     *
     * @param mid the value for QRC_PAYMENT_RECORD.MID
     *
     * @mbg.generated
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.TID
     *
     * @return the value of QRC_PAYMENT_RECORD.TID
     *
     * @mbg.generated
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.TID
     *
     * @param tid the value for QRC_PAYMENT_RECORD.TID
     *
     * @mbg.generated
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.ORDER_ID
     *
     * @return the value of QRC_PAYMENT_RECORD.ORDER_ID
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.ORDER_ID
     *
     * @param orderId the value for QRC_PAYMENT_RECORD.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.ORDER_DATE
     *
     * @return the value of QRC_PAYMENT_RECORD.ORDER_DATE
     *
     * @mbg.generated
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.ORDER_DATE
     *
     * @param orderDate the value for QRC_PAYMENT_RECORD.ORDER_DATE
     *
     * @mbg.generated
     */
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate == null ? null : orderDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.ORDER_TIME
     *
     * @return the value of QRC_PAYMENT_RECORD.ORDER_TIME
     *
     * @mbg.generated
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.ORDER_TIME
     *
     * @param orderTime the value for QRC_PAYMENT_RECORD.ORDER_TIME
     *
     * @mbg.generated
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.ORDER_TYPE
     *
     * @return the value of QRC_PAYMENT_RECORD.ORDER_TYPE
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.ORDER_TYPE
     *
     * @param orderType the value for QRC_PAYMENT_RECORD.ORDER_TYPE
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.PLATFORM_SEQ
     *
     * @return the value of QRC_PAYMENT_RECORD.PLATFORM_SEQ
     *
     * @mbg.generated
     */
    public String getPlatformSeq() {
        return platformSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.PLATFORM_SEQ
     *
     * @param platformSeq the value for QRC_PAYMENT_RECORD.PLATFORM_SEQ
     *
     * @mbg.generated
     */
    public void setPlatformSeq(String platformSeq) {
        this.platformSeq = platformSeq == null ? null : platformSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.QRC_CHANNEL
     *
     * @return the value of QRC_PAYMENT_RECORD.QRC_CHANNEL
     *
     * @mbg.generated
     */
    public String getQrcChannel() {
        return qrcChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.QRC_CHANNEL
     *
     * @param qrcChannel the value for QRC_PAYMENT_RECORD.QRC_CHANNEL
     *
     * @mbg.generated
     */
    public void setQrcChannel(String qrcChannel) {
        this.qrcChannel = qrcChannel == null ? null : qrcChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.QRC_CHANNEL_FLAG
     *
     * @return the value of QRC_PAYMENT_RECORD.QRC_CHANNEL_FLAG
     *
     * @mbg.generated
     */
    public String getQrcChannelFlag() {
        return qrcChannelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.QRC_CHANNEL_FLAG
     *
     * @param qrcChannelFlag the value for QRC_PAYMENT_RECORD.QRC_CHANNEL_FLAG
     *
     * @mbg.generated
     */
    public void setQrcChannelFlag(String qrcChannelFlag) {
        this.qrcChannelFlag = qrcChannelFlag == null ? null : qrcChannelFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.QRC_CHANNEL_MID
     *
     * @return the value of QRC_PAYMENT_RECORD.QRC_CHANNEL_MID
     *
     * @mbg.generated
     */
    public String getQrcChannelMid() {
        return qrcChannelMid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.QRC_CHANNEL_MID
     *
     * @param qrcChannelMid the value for QRC_PAYMENT_RECORD.QRC_CHANNEL_MID
     *
     * @mbg.generated
     */
    public void setQrcChannelMid(String qrcChannelMid) {
        this.qrcChannelMid = qrcChannelMid == null ? null : qrcChannelMid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.QRC_CHANNEL_TID
     *
     * @return the value of QRC_PAYMENT_RECORD.QRC_CHANNEL_TID
     *
     * @mbg.generated
     */
    public String getQrcChannelTid() {
        return qrcChannelTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.QRC_CHANNEL_TID
     *
     * @param qrcChannelTid the value for QRC_PAYMENT_RECORD.QRC_CHANNEL_TID
     *
     * @mbg.generated
     */
    public void setQrcChannelTid(String qrcChannelTid) {
        this.qrcChannelTid = qrcChannelTid == null ? null : qrcChannelTid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.QRC_PAYMENT_STATUS
     *
     * @return the value of QRC_PAYMENT_RECORD.QRC_PAYMENT_STATUS
     *
     * @mbg.generated
     */
    public String getQrcPaymentStatus() {
        return qrcPaymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.QRC_PAYMENT_STATUS
     *
     * @param qrcPaymentStatus the value for QRC_PAYMENT_RECORD.QRC_PAYMENT_STATUS
     *
     * @mbg.generated
     */
    public void setQrcPaymentStatus(String qrcPaymentStatus) {
        this.qrcPaymentStatus = qrcPaymentStatus == null ? null : qrcPaymentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.CARD_NO
     *
     * @return the value of QRC_PAYMENT_RECORD.CARD_NO
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.CARD_NO
     *
     * @param cardNo the value for QRC_PAYMENT_RECORD.CARD_NO
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.VIRTUAL_ACCT_NO
     *
     * @return the value of QRC_PAYMENT_RECORD.VIRTUAL_ACCT_NO
     *
     * @mbg.generated
     */
    public String getVirtualAcctNo() {
        return virtualAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.VIRTUAL_ACCT_NO
     *
     * @param virtualAcctNo the value for QRC_PAYMENT_RECORD.VIRTUAL_ACCT_NO
     *
     * @mbg.generated
     */
    public void setVirtualAcctNo(String virtualAcctNo) {
        this.virtualAcctNo = virtualAcctNo == null ? null : virtualAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.TRADE_AMOUNT
     *
     * @return the value of QRC_PAYMENT_RECORD.TRADE_AMOUNT
     *
     * @mbg.generated
     */
    public String getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.TRADE_AMOUNT
     *
     * @param tradeAmount the value for QRC_PAYMENT_RECORD.TRADE_AMOUNT
     *
     * @mbg.generated
     */
    public void setTradeAmount(String tradeAmount) {
        this.tradeAmount = tradeAmount == null ? null : tradeAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.FEE_AMOUNT
     *
     * @return the value of QRC_PAYMENT_RECORD.FEE_AMOUNT
     *
     * @mbg.generated
     */
    public String getFeeAmount() {
        return feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.FEE_AMOUNT
     *
     * @param feeAmount the value for QRC_PAYMENT_RECORD.FEE_AMOUNT
     *
     * @mbg.generated
     */
    public void setFeeAmount(String feeAmount) {
        this.feeAmount = feeAmount == null ? null : feeAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.NET_AMOUNT
     *
     * @return the value of QRC_PAYMENT_RECORD.NET_AMOUNT
     *
     * @mbg.generated
     */
    public String getNetAmount() {
        return netAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.NET_AMOUNT
     *
     * @param netAmount the value for QRC_PAYMENT_RECORD.NET_AMOUNT
     *
     * @mbg.generated
     */
    public void setNetAmount(String netAmount) {
        this.netAmount = netAmount == null ? null : netAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BENIFIT_AMOUNT
     *
     * @return the value of QRC_PAYMENT_RECORD.BENIFIT_AMOUNT
     *
     * @mbg.generated
     */
    public String getBenifitAmount() {
        return benifitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BENIFIT_AMOUNT
     *
     * @param benifitAmount the value for QRC_PAYMENT_RECORD.BENIFIT_AMOUNT
     *
     * @mbg.generated
     */
    public void setBenifitAmount(String benifitAmount) {
        this.benifitAmount = benifitAmount == null ? null : benifitAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.CREDIT_DEBIT_FLAG
     *
     * @return the value of QRC_PAYMENT_RECORD.CREDIT_DEBIT_FLAG
     *
     * @mbg.generated
     */
    public String getCreditDebitFlag() {
        return creditDebitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.CREDIT_DEBIT_FLAG
     *
     * @param creditDebitFlag the value for QRC_PAYMENT_RECORD.CREDIT_DEBIT_FLAG
     *
     * @mbg.generated
     */
    public void setCreditDebitFlag(String creditDebitFlag) {
        this.creditDebitFlag = creditDebitFlag == null ? null : creditDebitFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_SEND_MODE
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_SEND_MODE
     *
     * @mbg.generated
     */
    public String getBipiSendMode() {
        return bipiSendMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_SEND_MODE
     *
     * @param bipiSendMode the value for QRC_PAYMENT_RECORD.BIPI_SEND_MODE
     *
     * @mbg.generated
     */
    public void setBipiSendMode(String bipiSendMode) {
        this.bipiSendMode = bipiSendMode == null ? null : bipiSendMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_SEND_ID
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_SEND_ID
     *
     * @mbg.generated
     */
    public String getBipiSendId() {
        return bipiSendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_SEND_ID
     *
     * @param bipiSendId the value for QRC_PAYMENT_RECORD.BIPI_SEND_ID
     *
     * @mbg.generated
     */
    public void setBipiSendId(String bipiSendId) {
        this.bipiSendId = bipiSendId == null ? null : bipiSendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_SEND_DATE
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_SEND_DATE
     *
     * @mbg.generated
     */
    public String getBipiSendDate() {
        return bipiSendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_SEND_DATE
     *
     * @param bipiSendDate the value for QRC_PAYMENT_RECORD.BIPI_SEND_DATE
     *
     * @mbg.generated
     */
    public void setBipiSendDate(String bipiSendDate) {
        this.bipiSendDate = bipiSendDate == null ? null : bipiSendDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_SEND_TIME
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_SEND_TIME
     *
     * @mbg.generated
     */
    public String getBipiSendTime() {
        return bipiSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_SEND_TIME
     *
     * @param bipiSendTime the value for QRC_PAYMENT_RECORD.BIPI_SEND_TIME
     *
     * @mbg.generated
     */
    public void setBipiSendTime(String bipiSendTime) {
        this.bipiSendTime = bipiSendTime == null ? null : bipiSendTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_STATUS
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_STATUS
     *
     * @mbg.generated
     */
    public String getBipiStatus() {
        return bipiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_STATUS
     *
     * @param bipiStatus the value for QRC_PAYMENT_RECORD.BIPI_STATUS
     *
     * @mbg.generated
     */
    public void setBipiStatus(String bipiStatus) {
        this.bipiStatus = bipiStatus == null ? null : bipiStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_CODE
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_RESP_CODE
     *
     * @mbg.generated
     */
    public String getBipiRespCode() {
        return bipiRespCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_CODE
     *
     * @param bipiRespCode the value for QRC_PAYMENT_RECORD.BIPI_RESP_CODE
     *
     * @mbg.generated
     */
    public void setBipiRespCode(String bipiRespCode) {
        this.bipiRespCode = bipiRespCode == null ? null : bipiRespCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_MESSAGE
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_RESP_MESSAGE
     *
     * @mbg.generated
     */
    public String getBipiRespMessage() {
        return bipiRespMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_MESSAGE
     *
     * @param bipiRespMessage the value for QRC_PAYMENT_RECORD.BIPI_RESP_MESSAGE
     *
     * @mbg.generated
     */
    public void setBipiRespMessage(String bipiRespMessage) {
        this.bipiRespMessage = bipiRespMessage == null ? null : bipiRespMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_TRACE_ID
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_TRACE_ID
     *
     * @mbg.generated
     */
    public String getBipiTraceId() {
        return bipiTraceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_TRACE_ID
     *
     * @param bipiTraceId the value for QRC_PAYMENT_RECORD.BIPI_TRACE_ID
     *
     * @mbg.generated
     */
    public void setBipiTraceId(String bipiTraceId) {
        this.bipiTraceId = bipiTraceId == null ? null : bipiTraceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_DATE
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_RESP_DATE
     *
     * @mbg.generated
     */
    public String getBipiRespDate() {
        return bipiRespDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_DATE
     *
     * @param bipiRespDate the value for QRC_PAYMENT_RECORD.BIPI_RESP_DATE
     *
     * @mbg.generated
     */
    public void setBipiRespDate(String bipiRespDate) {
        this.bipiRespDate = bipiRespDate == null ? null : bipiRespDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_TIME
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_RESP_TIME
     *
     * @mbg.generated
     */
    public String getBipiRespTime() {
        return bipiRespTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_TIME
     *
     * @param bipiRespTime the value for QRC_PAYMENT_RECORD.BIPI_RESP_TIME
     *
     * @mbg.generated
     */
    public void setBipiRespTime(String bipiRespTime) {
        this.bipiRespTime = bipiRespTime == null ? null : bipiRespTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_RESV1
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_RESP_RESV1
     *
     * @mbg.generated
     */
    public String getBipiRespResv1() {
        return bipiRespResv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_RESV1
     *
     * @param bipiRespResv1 the value for QRC_PAYMENT_RECORD.BIPI_RESP_RESV1
     *
     * @mbg.generated
     */
    public void setBipiRespResv1(String bipiRespResv1) {
        this.bipiRespResv1 = bipiRespResv1 == null ? null : bipiRespResv1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_RESV2
     *
     * @return the value of QRC_PAYMENT_RECORD.BIPI_RESP_RESV2
     *
     * @mbg.generated
     */
    public String getBipiRespResv2() {
        return bipiRespResv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.BIPI_RESP_RESV2
     *
     * @param bipiRespResv2 the value for QRC_PAYMENT_RECORD.BIPI_RESP_RESV2
     *
     * @mbg.generated
     */
    public void setBipiRespResv2(String bipiRespResv2) {
        this.bipiRespResv2 = bipiRespResv2 == null ? null : bipiRespResv2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.CHECK_FLAG
     *
     * @return the value of QRC_PAYMENT_RECORD.CHECK_FLAG
     *
     * @mbg.generated
     */
    public String getCheckFlag() {
        return checkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.CHECK_FLAG
     *
     * @param checkFlag the value for QRC_PAYMENT_RECORD.CHECK_FLAG
     *
     * @mbg.generated
     */
    public void setCheckFlag(String checkFlag) {
        this.checkFlag = checkFlag == null ? null : checkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.CLEAR_DATE
     *
     * @return the value of QRC_PAYMENT_RECORD.CLEAR_DATE
     *
     * @mbg.generated
     */
    public String getClearDate() {
        return clearDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.CLEAR_DATE
     *
     * @param clearDate the value for QRC_PAYMENT_RECORD.CLEAR_DATE
     *
     * @mbg.generated
     */
    public void setClearDate(String clearDate) {
        this.clearDate = clearDate == null ? null : clearDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.PRINT_FLAG
     *
     * @return the value of QRC_PAYMENT_RECORD.PRINT_FLAG
     *
     * @mbg.generated
     */
    public String getPrintFlag() {
        return printFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.PRINT_FLAG
     *
     * @param printFlag the value for QRC_PAYMENT_RECORD.PRINT_FLAG
     *
     * @mbg.generated
     */
    public void setPrintFlag(String printFlag) {
        this.printFlag = printFlag == null ? null : printFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.REMARK
     *
     * @return the value of QRC_PAYMENT_RECORD.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.REMARK
     *
     * @param remark the value for QRC_PAYMENT_RECORD.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.PAYMENT_RESV1
     *
     * @return the value of QRC_PAYMENT_RECORD.PAYMENT_RESV1
     *
     * @mbg.generated
     */
    public String getPaymentResv1() {
        return paymentResv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.PAYMENT_RESV1
     *
     * @param paymentResv1 the value for QRC_PAYMENT_RECORD.PAYMENT_RESV1
     *
     * @mbg.generated
     */
    public void setPaymentResv1(String paymentResv1) {
        this.paymentResv1 = paymentResv1 == null ? null : paymentResv1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.PAYMENT_RESV2
     *
     * @return the value of QRC_PAYMENT_RECORD.PAYMENT_RESV2
     *
     * @mbg.generated
     */
    public String getPaymentResv2() {
        return paymentResv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.PAYMENT_RESV2
     *
     * @param paymentResv2 the value for QRC_PAYMENT_RECORD.PAYMENT_RESV2
     *
     * @mbg.generated
     */
    public void setPaymentResv2(String paymentResv2) {
        this.paymentResv2 = paymentResv2 == null ? null : paymentResv2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.PAYMENT_RESV3
     *
     * @return the value of QRC_PAYMENT_RECORD.PAYMENT_RESV3
     *
     * @mbg.generated
     */
    public String getPaymentResv3() {
        return paymentResv3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.PAYMENT_RESV3
     *
     * @param paymentResv3 the value for QRC_PAYMENT_RECORD.PAYMENT_RESV3
     *
     * @mbg.generated
     */
    public void setPaymentResv3(String paymentResv3) {
        this.paymentResv3 = paymentResv3 == null ? null : paymentResv3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRC_PAYMENT_RECORD.CANCEL_OR_REFUND
     *
     * @return the value of QRC_PAYMENT_RECORD.CANCEL_OR_REFUND
     *
     * @mbg.generated
     */
    public String getCancelOrRefund() {
        return cancelOrRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRC_PAYMENT_RECORD.CANCEL_OR_REFUND
     *
     * @param cancelOrRefund the value for QRC_PAYMENT_RECORD.CANCEL_OR_REFUND
     *
     * @mbg.generated
     */
    public void setCancelOrRefund(String cancelOrRefund) {
        this.cancelOrRefund = cancelOrRefund == null ? null : cancelOrRefund.trim();
    }
}