package com.company.core.entity;

public class TblBtsUsrMapDo extends TblBtsUsrMapDoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_USR_MAP.USR_TYPE
     *
     * @mbg.generated
     */
    private String usrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_USR_MAP.USER_CODE
     *
     * @mbg.generated
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_USR_MAP.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_USR_MAP.CREATE_SOURCE
     *
     * @mbg.generated
     */
    private String createSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_USR_MAP.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_USR_MAP.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_USR_MAP.MODIFY_SOURCE
     *
     * @mbg.generated
     */
    private String modifySource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_USR_MAP.MODIFY_USER
     *
     * @mbg.generated
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_USR_MAP.MODIFY_TIME
     *
     * @mbg.generated
     */
    private String modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BTS_USR_MAP.LOCK_VERSION
     *
     * @mbg.generated
     */
    private String lockVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_USR_MAP.USR_TYPE
     *
     * @return the value of TBL_BTS_USR_MAP.USR_TYPE
     *
     * @mbg.generated
     */
    public String getUsrType() {
        return usrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_USR_MAP.USR_TYPE
     *
     * @param usrType the value for TBL_BTS_USR_MAP.USR_TYPE
     *
     * @mbg.generated
     */
    public void setUsrType(String usrType) {
        this.usrType = usrType == null ? null : usrType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_USR_MAP.USER_CODE
     *
     * @return the value of TBL_BTS_USR_MAP.USER_CODE
     *
     * @mbg.generated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_USR_MAP.USER_CODE
     *
     * @param userCode the value for TBL_BTS_USR_MAP.USER_CODE
     *
     * @mbg.generated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_USR_MAP.USER_NAME
     *
     * @return the value of TBL_BTS_USR_MAP.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_USR_MAP.USER_NAME
     *
     * @param userName the value for TBL_BTS_USR_MAP.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_USR_MAP.CREATE_SOURCE
     *
     * @return the value of TBL_BTS_USR_MAP.CREATE_SOURCE
     *
     * @mbg.generated
     */
    public String getCreateSource() {
        return createSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_USR_MAP.CREATE_SOURCE
     *
     * @param createSource the value for TBL_BTS_USR_MAP.CREATE_SOURCE
     *
     * @mbg.generated
     */
    public void setCreateSource(String createSource) {
        this.createSource = createSource == null ? null : createSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_USR_MAP.CREATE_USER
     *
     * @return the value of TBL_BTS_USR_MAP.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_USR_MAP.CREATE_USER
     *
     * @param createUser the value for TBL_BTS_USR_MAP.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_USR_MAP.CREATE_TIME
     *
     * @return the value of TBL_BTS_USR_MAP.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_USR_MAP.CREATE_TIME
     *
     * @param createTime the value for TBL_BTS_USR_MAP.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_USR_MAP.MODIFY_SOURCE
     *
     * @return the value of TBL_BTS_USR_MAP.MODIFY_SOURCE
     *
     * @mbg.generated
     */
    public String getModifySource() {
        return modifySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_USR_MAP.MODIFY_SOURCE
     *
     * @param modifySource the value for TBL_BTS_USR_MAP.MODIFY_SOURCE
     *
     * @mbg.generated
     */
    public void setModifySource(String modifySource) {
        this.modifySource = modifySource == null ? null : modifySource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_USR_MAP.MODIFY_USER
     *
     * @return the value of TBL_BTS_USR_MAP.MODIFY_USER
     *
     * @mbg.generated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_USR_MAP.MODIFY_USER
     *
     * @param modifyUser the value for TBL_BTS_USR_MAP.MODIFY_USER
     *
     * @mbg.generated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_USR_MAP.MODIFY_TIME
     *
     * @return the value of TBL_BTS_USR_MAP.MODIFY_TIME
     *
     * @mbg.generated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_USR_MAP.MODIFY_TIME
     *
     * @param modifyTime the value for TBL_BTS_USR_MAP.MODIFY_TIME
     *
     * @mbg.generated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BTS_USR_MAP.LOCK_VERSION
     *
     * @return the value of TBL_BTS_USR_MAP.LOCK_VERSION
     *
     * @mbg.generated
     */
    public String getLockVersion() {
        return lockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BTS_USR_MAP.LOCK_VERSION
     *
     * @param lockVersion the value for TBL_BTS_USR_MAP.LOCK_VERSION
     *
     * @mbg.generated
     */
    public void setLockVersion(String lockVersion) {
        this.lockVersion = lockVersion == null ? null : lockVersion.trim();
    }
}