package com.company.core.entity;

public class UcCategoryDoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_CATEGORY.CATEGORY
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_CATEGORY.CATEGORY_ID
     *
     * @mbg.generated
     */
    private String categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_CATEGORY.CATEGORY
     *
     * @return the value of UC_CATEGORY.CATEGORY
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_CATEGORY.CATEGORY
     *
     * @param category the value for UC_CATEGORY.CATEGORY
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_CATEGORY.CATEGORY_ID
     *
     * @return the value of UC_CATEGORY.CATEGORY_ID
     *
     * @mbg.generated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_CATEGORY.CATEGORY_ID
     *
     * @param categoryId the value for UC_CATEGORY.CATEGORY_ID
     *
     * @mbg.generated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }
}