package com.company.core.entity;

public class UcProdDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_PROD.PROD_ID
     *
     * @mbg.generated
     */
    private String prodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_PROD.PROD_NAME
     *
     * @mbg.generated
     */
    private String prodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_PROD.PROD_STATUS
     *
     * @mbg.generated
     */
    private String prodStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_PROD.OPEN_DATE
     *
     * @mbg.generated
     */
    private String openDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_PROD.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_PROD.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_PROD.PROD_ID
     *
     * @return the value of UC_PROD.PROD_ID
     *
     * @mbg.generated
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_PROD.PROD_ID
     *
     * @param prodId the value for UC_PROD.PROD_ID
     *
     * @mbg.generated
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_PROD.PROD_NAME
     *
     * @return the value of UC_PROD.PROD_NAME
     *
     * @mbg.generated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_PROD.PROD_NAME
     *
     * @param prodName the value for UC_PROD.PROD_NAME
     *
     * @mbg.generated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_PROD.PROD_STATUS
     *
     * @return the value of UC_PROD.PROD_STATUS
     *
     * @mbg.generated
     */
    public String getProdStatus() {
        return prodStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_PROD.PROD_STATUS
     *
     * @param prodStatus the value for UC_PROD.PROD_STATUS
     *
     * @mbg.generated
     */
    public void setProdStatus(String prodStatus) {
        this.prodStatus = prodStatus == null ? null : prodStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_PROD.OPEN_DATE
     *
     * @return the value of UC_PROD.OPEN_DATE
     *
     * @mbg.generated
     */
    public String getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_PROD.OPEN_DATE
     *
     * @param openDate the value for UC_PROD.OPEN_DATE
     *
     * @mbg.generated
     */
    public void setOpenDate(String openDate) {
        this.openDate = openDate == null ? null : openDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_PROD.CREATE_TIME
     *
     * @return the value of UC_PROD.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_PROD.CREATE_TIME
     *
     * @param createTime the value for UC_PROD.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_PROD.UPDATE_TIME
     *
     * @return the value of UC_PROD.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_PROD.UPDATE_TIME
     *
     * @param updateTime the value for UC_PROD.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}