package com.company.core.entity;

public class UcRecomCodeUserRelDo extends UcRecomCodeUserRelDoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.CREATE_SOURCE
     *
     * @mbggenerated
     */
    private String createSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.MODIFY_USER
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.MODIFY_TIME
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    private String modifySource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.LOCK_VERSION
     *
     * @mbggenerated
     */
    private String lockVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.EXTEND1
     *
     * @mbggenerated
     */
    private String extend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.EXTEND2
     *
     * @mbggenerated
     */
    private String extend2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.CREATE_USER
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.CREATE_USER
     *
     * @param createUser the value for UC_RECCOM_CODE_USER_REL.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.CREATE_TIME
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.CREATE_TIME
     *
     * @param createTime the value for UC_RECCOM_CODE_USER_REL.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.CREATE_SOURCE
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.CREATE_SOURCE
     *
     * @mbggenerated
     */
    public String getCreateSource() {
        return createSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.CREATE_SOURCE
     *
     * @param createSource the value for UC_RECCOM_CODE_USER_REL.CREATE_SOURCE
     *
     * @mbggenerated
     */
    public void setCreateSource(String createSource) {
        this.createSource = createSource == null ? null : createSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.MODIFY_USER
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.MODIFY_USER
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.MODIFY_USER
     *
     * @param modifyUser the value for UC_RECCOM_CODE_USER_REL.MODIFY_USER
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.MODIFY_TIME
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.MODIFY_TIME
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.MODIFY_TIME
     *
     * @param modifyTime the value for UC_RECCOM_CODE_USER_REL.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.MODIFY_SOURCE
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    public String getModifySource() {
        return modifySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.MODIFY_SOURCE
     *
     * @param modifySource the value for UC_RECCOM_CODE_USER_REL.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    public void setModifySource(String modifySource) {
        this.modifySource = modifySource == null ? null : modifySource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.LOCK_VERSION
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.LOCK_VERSION
     *
     * @mbggenerated
     */
    public String getLockVersion() {
        return lockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.LOCK_VERSION
     *
     * @param lockVersion the value for UC_RECCOM_CODE_USER_REL.LOCK_VERSION
     *
     * @mbggenerated
     */
    public void setLockVersion(String lockVersion) {
        this.lockVersion = lockVersion == null ? null : lockVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.EXTEND1
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.EXTEND1
     *
     * @mbggenerated
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.EXTEND1
     *
     * @param extend1 the value for UC_RECCOM_CODE_USER_REL.EXTEND1
     *
     * @mbggenerated
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.EXTEND2
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.EXTEND2
     *
     * @mbggenerated
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.EXTEND2
     *
     * @param extend2 the value for UC_RECCOM_CODE_USER_REL.EXTEND2
     *
     * @mbggenerated
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }
}