package com.company.core.entity;

public class UcRecomCodeUserRelDoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.RECCOM_CODE
     *
     * @mbggenerated
     */
    private String reccomCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.USER_TYPE
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_USER_REL.USER_CODE
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.RECCOM_CODE
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.RECCOM_CODE
     *
     * @mbggenerated
     */
    public String getReccomCode() {
        return reccomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.RECCOM_CODE
     *
     * @param reccomCode the value for UC_RECCOM_CODE_USER_REL.RECCOM_CODE
     *
     * @mbggenerated
     */
    public void setReccomCode(String reccomCode) {
        this.reccomCode = reccomCode == null ? null : reccomCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.USER_TYPE
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.USER_TYPE
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.USER_TYPE
     *
     * @param userType the value for UC_RECCOM_CODE_USER_REL.USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_USER_REL.USER_CODE
     *
     * @return the value of UC_RECCOM_CODE_USER_REL.USER_CODE
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_USER_REL.USER_CODE
     *
     * @param userCode the value for UC_RECCOM_CODE_USER_REL.USER_CODE
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }
}