package com.company.core.entity;

import java.math.BigDecimal;

public class UcReccomCodeCntlDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE
     *
     * @mbggenerated
     */
    private String reccomCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.CATEGORY
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.CATEGORY_ID
     *
     * @mbggenerated
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.USER_TYPE
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.USER_CODE
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.BATCH_ID
     *
     * @mbggenerated
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE_SEQ
     *
     * @mbggenerated
     */
    private String reccomCodeSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE_PATH
     *
     * @mbggenerated
     */
    private String reccomCodePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.MAX_USTING_TIMES
     *
     * @mbggenerated
     */
    private BigDecimal maxUstingTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.PWD_REQUIRED
     *
     * @mbggenerated
     */
    private String pwdRequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE_PWD
     *
     * @mbggenerated
     */
    private String reccomCodePwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.EXPIRE_DATE
     *
     * @mbggenerated
     */
    private String expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.PRICE
     *
     * @mbggenerated
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.CREATE_SOURCE
     *
     * @mbggenerated
     */
    private String createSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.MODIFY_USER
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.MODIFY_TIME
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    private String modifySource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.LOCK_VERSION
     *
     * @mbggenerated
     */
    private String lockVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.EXTEND1
     *
     * @mbggenerated
     */
    private String extend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_RECCOM_CODE_CNTL.EXTEND2
     *
     * @mbggenerated
     */
    private String extend2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE
     *
     * @return the value of UC_RECCOM_CODE_CNTL.RECCOM_CODE
     *
     * @mbggenerated
     */
    public String getReccomCode() {
        return reccomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE
     *
     * @param reccomCode the value for UC_RECCOM_CODE_CNTL.RECCOM_CODE
     *
     * @mbggenerated
     */
    public void setReccomCode(String reccomCode) {
        this.reccomCode = reccomCode == null ? null : reccomCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.TYPE
     *
     * @return the value of UC_RECCOM_CODE_CNTL.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.TYPE
     *
     * @param type the value for UC_RECCOM_CODE_CNTL.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.CATEGORY
     *
     * @return the value of UC_RECCOM_CODE_CNTL.CATEGORY
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.CATEGORY
     *
     * @param category the value for UC_RECCOM_CODE_CNTL.CATEGORY
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.CATEGORY_ID
     *
     * @return the value of UC_RECCOM_CODE_CNTL.CATEGORY_ID
     *
     * @mbggenerated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.CATEGORY_ID
     *
     * @param categoryId the value for UC_RECCOM_CODE_CNTL.CATEGORY_ID
     *
     * @mbggenerated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.USER_TYPE
     *
     * @return the value of UC_RECCOM_CODE_CNTL.USER_TYPE
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.USER_TYPE
     *
     * @param userType the value for UC_RECCOM_CODE_CNTL.USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.USER_CODE
     *
     * @return the value of UC_RECCOM_CODE_CNTL.USER_CODE
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.USER_CODE
     *
     * @param userCode the value for UC_RECCOM_CODE_CNTL.USER_CODE
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.BATCH_ID
     *
     * @return the value of UC_RECCOM_CODE_CNTL.BATCH_ID
     *
     * @mbggenerated
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.BATCH_ID
     *
     * @param batchId the value for UC_RECCOM_CODE_CNTL.BATCH_ID
     *
     * @mbggenerated
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE_SEQ
     *
     * @return the value of UC_RECCOM_CODE_CNTL.RECCOM_CODE_SEQ
     *
     * @mbggenerated
     */
    public String getReccomCodeSeq() {
        return reccomCodeSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE_SEQ
     *
     * @param reccomCodeSeq the value for UC_RECCOM_CODE_CNTL.RECCOM_CODE_SEQ
     *
     * @mbggenerated
     */
    public void setReccomCodeSeq(String reccomCodeSeq) {
        this.reccomCodeSeq = reccomCodeSeq == null ? null : reccomCodeSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE_PATH
     *
     * @return the value of UC_RECCOM_CODE_CNTL.RECCOM_CODE_PATH
     *
     * @mbggenerated
     */
    public String getReccomCodePath() {
        return reccomCodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE_PATH
     *
     * @param reccomCodePath the value for UC_RECCOM_CODE_CNTL.RECCOM_CODE_PATH
     *
     * @mbggenerated
     */
    public void setReccomCodePath(String reccomCodePath) {
        this.reccomCodePath = reccomCodePath == null ? null : reccomCodePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.STATUS
     *
     * @return the value of UC_RECCOM_CODE_CNTL.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.STATUS
     *
     * @param status the value for UC_RECCOM_CODE_CNTL.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.MAX_USTING_TIMES
     *
     * @return the value of UC_RECCOM_CODE_CNTL.MAX_USTING_TIMES
     *
     * @mbggenerated
     */
    public BigDecimal getMaxUstingTimes() {
        return maxUstingTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.MAX_USTING_TIMES
     *
     * @param maxUstingTimes the value for UC_RECCOM_CODE_CNTL.MAX_USTING_TIMES
     *
     * @mbggenerated
     */
    public void setMaxUstingTimes(BigDecimal maxUstingTimes) {
        this.maxUstingTimes = maxUstingTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.PWD_REQUIRED
     *
     * @return the value of UC_RECCOM_CODE_CNTL.PWD_REQUIRED
     *
     * @mbggenerated
     */
    public String getPwdRequired() {
        return pwdRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.PWD_REQUIRED
     *
     * @param pwdRequired the value for UC_RECCOM_CODE_CNTL.PWD_REQUIRED
     *
     * @mbggenerated
     */
    public void setPwdRequired(String pwdRequired) {
        this.pwdRequired = pwdRequired == null ? null : pwdRequired.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE_PWD
     *
     * @return the value of UC_RECCOM_CODE_CNTL.RECCOM_CODE_PWD
     *
     * @mbggenerated
     */
    public String getReccomCodePwd() {
        return reccomCodePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.RECCOM_CODE_PWD
     *
     * @param reccomCodePwd the value for UC_RECCOM_CODE_CNTL.RECCOM_CODE_PWD
     *
     * @mbggenerated
     */
    public void setReccomCodePwd(String reccomCodePwd) {
        this.reccomCodePwd = reccomCodePwd == null ? null : reccomCodePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.EXPIRE_DATE
     *
     * @return the value of UC_RECCOM_CODE_CNTL.EXPIRE_DATE
     *
     * @mbggenerated
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.EXPIRE_DATE
     *
     * @param expireDate the value for UC_RECCOM_CODE_CNTL.EXPIRE_DATE
     *
     * @mbggenerated
     */
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate == null ? null : expireDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.PRICE
     *
     * @return the value of UC_RECCOM_CODE_CNTL.PRICE
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.PRICE
     *
     * @param price the value for UC_RECCOM_CODE_CNTL.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.CREATE_USER
     *
     * @return the value of UC_RECCOM_CODE_CNTL.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.CREATE_USER
     *
     * @param createUser the value for UC_RECCOM_CODE_CNTL.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.CREATE_TIME
     *
     * @return the value of UC_RECCOM_CODE_CNTL.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.CREATE_TIME
     *
     * @param createTime the value for UC_RECCOM_CODE_CNTL.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.CREATE_SOURCE
     *
     * @return the value of UC_RECCOM_CODE_CNTL.CREATE_SOURCE
     *
     * @mbggenerated
     */
    public String getCreateSource() {
        return createSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.CREATE_SOURCE
     *
     * @param createSource the value for UC_RECCOM_CODE_CNTL.CREATE_SOURCE
     *
     * @mbggenerated
     */
    public void setCreateSource(String createSource) {
        this.createSource = createSource == null ? null : createSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.MODIFY_USER
     *
     * @return the value of UC_RECCOM_CODE_CNTL.MODIFY_USER
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.MODIFY_USER
     *
     * @param modifyUser the value for UC_RECCOM_CODE_CNTL.MODIFY_USER
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.MODIFY_TIME
     *
     * @return the value of UC_RECCOM_CODE_CNTL.MODIFY_TIME
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.MODIFY_TIME
     *
     * @param modifyTime the value for UC_RECCOM_CODE_CNTL.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.MODIFY_SOURCE
     *
     * @return the value of UC_RECCOM_CODE_CNTL.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    public String getModifySource() {
        return modifySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.MODIFY_SOURCE
     *
     * @param modifySource the value for UC_RECCOM_CODE_CNTL.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    public void setModifySource(String modifySource) {
        this.modifySource = modifySource == null ? null : modifySource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.LOCK_VERSION
     *
     * @return the value of UC_RECCOM_CODE_CNTL.LOCK_VERSION
     *
     * @mbggenerated
     */
    public String getLockVersion() {
        return lockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.LOCK_VERSION
     *
     * @param lockVersion the value for UC_RECCOM_CODE_CNTL.LOCK_VERSION
     *
     * @mbggenerated
     */
    public void setLockVersion(String lockVersion) {
        this.lockVersion = lockVersion == null ? null : lockVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.EXTEND1
     *
     * @return the value of UC_RECCOM_CODE_CNTL.EXTEND1
     *
     * @mbggenerated
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.EXTEND1
     *
     * @param extend1 the value for UC_RECCOM_CODE_CNTL.EXTEND1
     *
     * @mbggenerated
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_RECCOM_CODE_CNTL.EXTEND2
     *
     * @return the value of UC_RECCOM_CODE_CNTL.EXTEND2
     *
     * @mbggenerated
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_RECCOM_CODE_CNTL.EXTEND2
     *
     * @param extend2 the value for UC_RECCOM_CODE_CNTL.EXTEND2
     *
     * @mbggenerated
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }
}