package com.company.core.entity;

public class UcUserProdDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_PROD.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_PROD.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_PROD.PROD_ID
     *
     * @mbg.generated
     */
    private String prodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_PROD.PROD_NAME
     *
     * @mbg.generated
     */
    private String prodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_PROD.OPEN_STATUS
     *
     * @mbg.generated
     */
    private String openStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_PROD.OPEN_METHOD
     *
     * @mbg.generated
     */
    private String openMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_PROD.OPEN_SOURCE
     *
     * @mbg.generated
     */
    private String openSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_PROD.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_PROD.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_PROD.ID
     *
     * @return the value of UC_USER_PROD.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_PROD.ID
     *
     * @param id the value for UC_USER_PROD.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_PROD.USER_ID
     *
     * @return the value of UC_USER_PROD.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_PROD.USER_ID
     *
     * @param userId the value for UC_USER_PROD.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_PROD.PROD_ID
     *
     * @return the value of UC_USER_PROD.PROD_ID
     *
     * @mbg.generated
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_PROD.PROD_ID
     *
     * @param prodId the value for UC_USER_PROD.PROD_ID
     *
     * @mbg.generated
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_PROD.PROD_NAME
     *
     * @return the value of UC_USER_PROD.PROD_NAME
     *
     * @mbg.generated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_PROD.PROD_NAME
     *
     * @param prodName the value for UC_USER_PROD.PROD_NAME
     *
     * @mbg.generated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_PROD.OPEN_STATUS
     *
     * @return the value of UC_USER_PROD.OPEN_STATUS
     *
     * @mbg.generated
     */
    public String getOpenStatus() {
        return openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_PROD.OPEN_STATUS
     *
     * @param openStatus the value for UC_USER_PROD.OPEN_STATUS
     *
     * @mbg.generated
     */
    public void setOpenStatus(String openStatus) {
        this.openStatus = openStatus == null ? null : openStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_PROD.OPEN_METHOD
     *
     * @return the value of UC_USER_PROD.OPEN_METHOD
     *
     * @mbg.generated
     */
    public String getOpenMethod() {
        return openMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_PROD.OPEN_METHOD
     *
     * @param openMethod the value for UC_USER_PROD.OPEN_METHOD
     *
     * @mbg.generated
     */
    public void setOpenMethod(String openMethod) {
        this.openMethod = openMethod == null ? null : openMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_PROD.OPEN_SOURCE
     *
     * @return the value of UC_USER_PROD.OPEN_SOURCE
     *
     * @mbg.generated
     */
    public String getOpenSource() {
        return openSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_PROD.OPEN_SOURCE
     *
     * @param openSource the value for UC_USER_PROD.OPEN_SOURCE
     *
     * @mbg.generated
     */
    public void setOpenSource(String openSource) {
        this.openSource = openSource == null ? null : openSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_PROD.CREATE_TIME
     *
     * @return the value of UC_USER_PROD.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_PROD.CREATE_TIME
     *
     * @param createTime the value for UC_USER_PROD.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_PROD.UPDATE_TIME
     *
     * @return the value of UC_USER_PROD.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_PROD.UPDATE_TIME
     *
     * @param updateTime the value for UC_USER_PROD.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}