package com.company.core.entity;

public class UcUserCarDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_TYPE
     *
     * @mbggenerated
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_PLATE_NO
     *
     * @mbggenerated
     */
    private String carPlateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_VIN_NO
     *
     * @mbggenerated
     */
    private String carVinNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_VIN_NO_LAST6
     *
     * @mbggenerated
     */
    private String carVinNoLast6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_ENGINE_NO
     *
     * @mbggenerated
     */
    private String carEngineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_LICENCE_NO
     *
     * @mbggenerated
     */
    private String carLicenceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_LICENCE_UP_PIC
     *
     * @mbggenerated
     */
    private String carLicenceUpPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_LICENCE_BUTTOM_PIC
     *
     * @mbggenerated
     */
    private String carLicenceButtomPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_DRIVER_LICENCE_UP_PIC
     *
     * @mbggenerated
     */
    private String carDriverLicenceUpPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_DRIVER_LICENCE_BUTTOM_PIC
     *
     * @mbggenerated
     */
    private String carDriverLicenceButtomPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_STRONG_INSURANCE_PIC
     *
     * @mbggenerated
     */
    private String carStrongInsurancePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_STRONG_INSURANCE_BAK_PIC
     *
     * @mbggenerated
     */
    private String carStrongInsuranceBakPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_RESV1
     *
     * @mbggenerated
     */
    private String carResv1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_RESV2
     *
     * @mbggenerated
     */
    private String carResv2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CAR_RESV3
     *
     * @mbggenerated
     */
    private String carResv3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    private String modifySource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.MODIFY_USER
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UC_USER_CAR.LOCK_VERSION
     *
     * @mbggenerated
     */
    private String lockVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.ID
     *
     * @return the value of UC_USER_CAR.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.ID
     *
     * @param id the value for UC_USER_CAR.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.USER_ID
     *
     * @return the value of UC_USER_CAR.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.USER_ID
     *
     * @param userId the value for UC_USER_CAR.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_TYPE
     *
     * @return the value of UC_USER_CAR.CAR_TYPE
     *
     * @mbggenerated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_TYPE
     *
     * @param carType the value for UC_USER_CAR.CAR_TYPE
     *
     * @mbggenerated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_PLATE_NO
     *
     * @return the value of UC_USER_CAR.CAR_PLATE_NO
     *
     * @mbggenerated
     */
    public String getCarPlateNo() {
        return carPlateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_PLATE_NO
     *
     * @param carPlateNo the value for UC_USER_CAR.CAR_PLATE_NO
     *
     * @mbggenerated
     */
    public void setCarPlateNo(String carPlateNo) {
        this.carPlateNo = carPlateNo == null ? null : carPlateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_VIN_NO
     *
     * @return the value of UC_USER_CAR.CAR_VIN_NO
     *
     * @mbggenerated
     */
    public String getCarVinNo() {
        return carVinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_VIN_NO
     *
     * @param carVinNo the value for UC_USER_CAR.CAR_VIN_NO
     *
     * @mbggenerated
     */
    public void setCarVinNo(String carVinNo) {
        this.carVinNo = carVinNo == null ? null : carVinNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_VIN_NO_LAST6
     *
     * @return the value of UC_USER_CAR.CAR_VIN_NO_LAST6
     *
     * @mbggenerated
     */
    public String getCarVinNoLast6() {
        return carVinNoLast6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_VIN_NO_LAST6
     *
     * @param carVinNoLast6 the value for UC_USER_CAR.CAR_VIN_NO_LAST6
     *
     * @mbggenerated
     */
    public void setCarVinNoLast6(String carVinNoLast6) {
        this.carVinNoLast6 = carVinNoLast6 == null ? null : carVinNoLast6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_ENGINE_NO
     *
     * @return the value of UC_USER_CAR.CAR_ENGINE_NO
     *
     * @mbggenerated
     */
    public String getCarEngineNo() {
        return carEngineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_ENGINE_NO
     *
     * @param carEngineNo the value for UC_USER_CAR.CAR_ENGINE_NO
     *
     * @mbggenerated
     */
    public void setCarEngineNo(String carEngineNo) {
        this.carEngineNo = carEngineNo == null ? null : carEngineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_LICENCE_NO
     *
     * @return the value of UC_USER_CAR.CAR_LICENCE_NO
     *
     * @mbggenerated
     */
    public String getCarLicenceNo() {
        return carLicenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_LICENCE_NO
     *
     * @param carLicenceNo the value for UC_USER_CAR.CAR_LICENCE_NO
     *
     * @mbggenerated
     */
    public void setCarLicenceNo(String carLicenceNo) {
        this.carLicenceNo = carLicenceNo == null ? null : carLicenceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_LICENCE_UP_PIC
     *
     * @return the value of UC_USER_CAR.CAR_LICENCE_UP_PIC
     *
     * @mbggenerated
     */
    public String getCarLicenceUpPic() {
        return carLicenceUpPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_LICENCE_UP_PIC
     *
     * @param carLicenceUpPic the value for UC_USER_CAR.CAR_LICENCE_UP_PIC
     *
     * @mbggenerated
     */
    public void setCarLicenceUpPic(String carLicenceUpPic) {
        this.carLicenceUpPic = carLicenceUpPic == null ? null : carLicenceUpPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_LICENCE_BUTTOM_PIC
     *
     * @return the value of UC_USER_CAR.CAR_LICENCE_BUTTOM_PIC
     *
     * @mbggenerated
     */
    public String getCarLicenceButtomPic() {
        return carLicenceButtomPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_LICENCE_BUTTOM_PIC
     *
     * @param carLicenceButtomPic the value for UC_USER_CAR.CAR_LICENCE_BUTTOM_PIC
     *
     * @mbggenerated
     */
    public void setCarLicenceButtomPic(String carLicenceButtomPic) {
        this.carLicenceButtomPic = carLicenceButtomPic == null ? null : carLicenceButtomPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_DRIVER_LICENCE_UP_PIC
     *
     * @return the value of UC_USER_CAR.CAR_DRIVER_LICENCE_UP_PIC
     *
     * @mbggenerated
     */
    public String getCarDriverLicenceUpPic() {
        return carDriverLicenceUpPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_DRIVER_LICENCE_UP_PIC
     *
     * @param carDriverLicenceUpPic the value for UC_USER_CAR.CAR_DRIVER_LICENCE_UP_PIC
     *
     * @mbggenerated
     */
    public void setCarDriverLicenceUpPic(String carDriverLicenceUpPic) {
        this.carDriverLicenceUpPic = carDriverLicenceUpPic == null ? null : carDriverLicenceUpPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_DRIVER_LICENCE_BUTTOM_PIC
     *
     * @return the value of UC_USER_CAR.CAR_DRIVER_LICENCE_BUTTOM_PIC
     *
     * @mbggenerated
     */
    public String getCarDriverLicenceButtomPic() {
        return carDriverLicenceButtomPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_DRIVER_LICENCE_BUTTOM_PIC
     *
     * @param carDriverLicenceButtomPic the value for UC_USER_CAR.CAR_DRIVER_LICENCE_BUTTOM_PIC
     *
     * @mbggenerated
     */
    public void setCarDriverLicenceButtomPic(String carDriverLicenceButtomPic) {
        this.carDriverLicenceButtomPic = carDriverLicenceButtomPic == null ? null : carDriverLicenceButtomPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_STRONG_INSURANCE_PIC
     *
     * @return the value of UC_USER_CAR.CAR_STRONG_INSURANCE_PIC
     *
     * @mbggenerated
     */
    public String getCarStrongInsurancePic() {
        return carStrongInsurancePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_STRONG_INSURANCE_PIC
     *
     * @param carStrongInsurancePic the value for UC_USER_CAR.CAR_STRONG_INSURANCE_PIC
     *
     * @mbggenerated
     */
    public void setCarStrongInsurancePic(String carStrongInsurancePic) {
        this.carStrongInsurancePic = carStrongInsurancePic == null ? null : carStrongInsurancePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_STRONG_INSURANCE_BAK_PIC
     *
     * @return the value of UC_USER_CAR.CAR_STRONG_INSURANCE_BAK_PIC
     *
     * @mbggenerated
     */
    public String getCarStrongInsuranceBakPic() {
        return carStrongInsuranceBakPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_STRONG_INSURANCE_BAK_PIC
     *
     * @param carStrongInsuranceBakPic the value for UC_USER_CAR.CAR_STRONG_INSURANCE_BAK_PIC
     *
     * @mbggenerated
     */
    public void setCarStrongInsuranceBakPic(String carStrongInsuranceBakPic) {
        this.carStrongInsuranceBakPic = carStrongInsuranceBakPic == null ? null : carStrongInsuranceBakPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_RESV1
     *
     * @return the value of UC_USER_CAR.CAR_RESV1
     *
     * @mbggenerated
     */
    public String getCarResv1() {
        return carResv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_RESV1
     *
     * @param carResv1 the value for UC_USER_CAR.CAR_RESV1
     *
     * @mbggenerated
     */
    public void setCarResv1(String carResv1) {
        this.carResv1 = carResv1 == null ? null : carResv1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_RESV2
     *
     * @return the value of UC_USER_CAR.CAR_RESV2
     *
     * @mbggenerated
     */
    public String getCarResv2() {
        return carResv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_RESV2
     *
     * @param carResv2 the value for UC_USER_CAR.CAR_RESV2
     *
     * @mbggenerated
     */
    public void setCarResv2(String carResv2) {
        this.carResv2 = carResv2 == null ? null : carResv2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CAR_RESV3
     *
     * @return the value of UC_USER_CAR.CAR_RESV3
     *
     * @mbggenerated
     */
    public String getCarResv3() {
        return carResv3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CAR_RESV3
     *
     * @param carResv3 the value for UC_USER_CAR.CAR_RESV3
     *
     * @mbggenerated
     */
    public void setCarResv3(String carResv3) {
        this.carResv3 = carResv3 == null ? null : carResv3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.MODIFY_SOURCE
     *
     * @return the value of UC_USER_CAR.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    public String getModifySource() {
        return modifySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.MODIFY_SOURCE
     *
     * @param modifySource the value for UC_USER_CAR.MODIFY_SOURCE
     *
     * @mbggenerated
     */
    public void setModifySource(String modifySource) {
        this.modifySource = modifySource == null ? null : modifySource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.MODIFY_USER
     *
     * @return the value of UC_USER_CAR.MODIFY_USER
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.MODIFY_USER
     *
     * @param modifyUser the value for UC_USER_CAR.MODIFY_USER
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.CREATE_TIME
     *
     * @return the value of UC_USER_CAR.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.CREATE_TIME
     *
     * @param createTime the value for UC_USER_CAR.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.UPDATE_TIME
     *
     * @return the value of UC_USER_CAR.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.UPDATE_TIME
     *
     * @param updateTime the value for UC_USER_CAR.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UC_USER_CAR.LOCK_VERSION
     *
     * @return the value of UC_USER_CAR.LOCK_VERSION
     *
     * @mbggenerated
     */
    public String getLockVersion() {
        return lockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UC_USER_CAR.LOCK_VERSION
     *
     * @param lockVersion the value for UC_USER_CAR.LOCK_VERSION
     *
     * @mbggenerated
     */
    public void setLockVersion(String lockVersion) {
        this.lockVersion = lockVersion == null ? null : lockVersion.trim();
    }
}