package com.company.core.entity;

public class WZBalanceInfoDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.ORG_ID
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.USER_MONEY
     *
     * @mbg.generated
     */
    private String userMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.COMPANY_NAME
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.ADD_TIME
     *
     * @mbg.generated
     */
    private String addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.CAR_WZ_NOTICE_URL
     *
     * @mbg.generated
     */
    private String carWzNoticeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.EXT1
     *
     * @mbg.generated
     */
    private String ext1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.EXT2
     *
     * @mbg.generated
     */
    private String ext2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.EXT3
     *
     * @mbg.generated
     */
    private String ext3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.EXT4
     *
     * @mbg.generated
     */
    private String ext4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.EXT5
     *
     * @mbg.generated
     */
    private String ext5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.EXT6
     *
     * @mbg.generated
     */
    private String ext6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.MODIFY_SOURCE
     *
     * @mbg.generated
     */
    private String modifySource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.MODIFY_USER
     *
     * @mbg.generated
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.LOCK_VERSION
     *
     * @mbg.generated
     */
    private String lockVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_BALANCE_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.ORG_ID
     *
     * @return the value of WZ_BALANCE_INFO.ORG_ID
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.ORG_ID
     *
     * @param orgId the value for WZ_BALANCE_INFO.ORG_ID
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.USER_NAME
     *
     * @return the value of WZ_BALANCE_INFO.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.USER_NAME
     *
     * @param userName the value for WZ_BALANCE_INFO.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.USER_MONEY
     *
     * @return the value of WZ_BALANCE_INFO.USER_MONEY
     *
     * @mbg.generated
     */
    public String getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.USER_MONEY
     *
     * @param userMoney the value for WZ_BALANCE_INFO.USER_MONEY
     *
     * @mbg.generated
     */
    public void setUserMoney(String userMoney) {
        this.userMoney = userMoney == null ? null : userMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.COMPANY_NAME
     *
     * @return the value of WZ_BALANCE_INFO.COMPANY_NAME
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.COMPANY_NAME
     *
     * @param companyName the value for WZ_BALANCE_INFO.COMPANY_NAME
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.ADD_TIME
     *
     * @return the value of WZ_BALANCE_INFO.ADD_TIME
     *
     * @mbg.generated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.ADD_TIME
     *
     * @param addTime the value for WZ_BALANCE_INFO.ADD_TIME
     *
     * @mbg.generated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime == null ? null : addTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.CAR_WZ_NOTICE_URL
     *
     * @return the value of WZ_BALANCE_INFO.CAR_WZ_NOTICE_URL
     *
     * @mbg.generated
     */
    public String getCarWzNoticeUrl() {
        return carWzNoticeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.CAR_WZ_NOTICE_URL
     *
     * @param carWzNoticeUrl the value for WZ_BALANCE_INFO.CAR_WZ_NOTICE_URL
     *
     * @mbg.generated
     */
    public void setCarWzNoticeUrl(String carWzNoticeUrl) {
        this.carWzNoticeUrl = carWzNoticeUrl == null ? null : carWzNoticeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.EXT1
     *
     * @return the value of WZ_BALANCE_INFO.EXT1
     *
     * @mbg.generated
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.EXT1
     *
     * @param ext1 the value for WZ_BALANCE_INFO.EXT1
     *
     * @mbg.generated
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.EXT2
     *
     * @return the value of WZ_BALANCE_INFO.EXT2
     *
     * @mbg.generated
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.EXT2
     *
     * @param ext2 the value for WZ_BALANCE_INFO.EXT2
     *
     * @mbg.generated
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.EXT3
     *
     * @return the value of WZ_BALANCE_INFO.EXT3
     *
     * @mbg.generated
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.EXT3
     *
     * @param ext3 the value for WZ_BALANCE_INFO.EXT3
     *
     * @mbg.generated
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.EXT4
     *
     * @return the value of WZ_BALANCE_INFO.EXT4
     *
     * @mbg.generated
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.EXT4
     *
     * @param ext4 the value for WZ_BALANCE_INFO.EXT4
     *
     * @mbg.generated
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.EXT5
     *
     * @return the value of WZ_BALANCE_INFO.EXT5
     *
     * @mbg.generated
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.EXT5
     *
     * @param ext5 the value for WZ_BALANCE_INFO.EXT5
     *
     * @mbg.generated
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.EXT6
     *
     * @return the value of WZ_BALANCE_INFO.EXT6
     *
     * @mbg.generated
     */
    public String getExt6() {
        return ext6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.EXT6
     *
     * @param ext6 the value for WZ_BALANCE_INFO.EXT6
     *
     * @mbg.generated
     */
    public void setExt6(String ext6) {
        this.ext6 = ext6 == null ? null : ext6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.MODIFY_SOURCE
     *
     * @return the value of WZ_BALANCE_INFO.MODIFY_SOURCE
     *
     * @mbg.generated
     */
    public String getModifySource() {
        return modifySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.MODIFY_SOURCE
     *
     * @param modifySource the value for WZ_BALANCE_INFO.MODIFY_SOURCE
     *
     * @mbg.generated
     */
    public void setModifySource(String modifySource) {
        this.modifySource = modifySource == null ? null : modifySource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.MODIFY_USER
     *
     * @return the value of WZ_BALANCE_INFO.MODIFY_USER
     *
     * @mbg.generated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.MODIFY_USER
     *
     * @param modifyUser the value for WZ_BALANCE_INFO.MODIFY_USER
     *
     * @mbg.generated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.LOCK_VERSION
     *
     * @return the value of WZ_BALANCE_INFO.LOCK_VERSION
     *
     * @mbg.generated
     */
    public String getLockVersion() {
        return lockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.LOCK_VERSION
     *
     * @param lockVersion the value for WZ_BALANCE_INFO.LOCK_VERSION
     *
     * @mbg.generated
     */
    public void setLockVersion(String lockVersion) {
        this.lockVersion = lockVersion == null ? null : lockVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.CREATE_TIME
     *
     * @return the value of WZ_BALANCE_INFO.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.CREATE_TIME
     *
     * @param createTime the value for WZ_BALANCE_INFO.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_BALANCE_INFO.UPDATE_TIME
     *
     * @return the value of WZ_BALANCE_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_BALANCE_INFO.UPDATE_TIME
     *
     * @param updateTime the value for WZ_BALANCE_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}