package com.company.core.entity;

import java.util.ArrayList;
import java.util.List;

public class WZExeOrderDoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public WZExeOrderDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("ORDER_ID =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("ORDER_ID <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("ORDER_ID >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_ID >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("ORDER_ID <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("ORDER_ID <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("ORDER_ID like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("ORDER_ID not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("ORDER_ID in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("ORDER_ID not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("ORDER_ID between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("ORDER_ID not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTotAmountIsNull() {
            addCriterion("TOT_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTotAmountIsNotNull() {
            addCriterion("TOT_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTotAmountEqualTo(String value) {
            addCriterion("TOT_AMOUNT =", value, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountNotEqualTo(String value) {
            addCriterion("TOT_AMOUNT <>", value, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountGreaterThan(String value) {
            addCriterion("TOT_AMOUNT >", value, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountGreaterThanOrEqualTo(String value) {
            addCriterion("TOT_AMOUNT >=", value, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountLessThan(String value) {
            addCriterion("TOT_AMOUNT <", value, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountLessThanOrEqualTo(String value) {
            addCriterion("TOT_AMOUNT <=", value, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountLike(String value) {
            addCriterion("TOT_AMOUNT like", value, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountNotLike(String value) {
            addCriterion("TOT_AMOUNT not like", value, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountIn(List<String> values) {
            addCriterion("TOT_AMOUNT in", values, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountNotIn(List<String> values) {
            addCriterion("TOT_AMOUNT not in", values, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountBetween(String value1, String value2) {
            addCriterion("TOT_AMOUNT between", value1, value2, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotAmountNotBetween(String value1, String value2) {
            addCriterion("TOT_AMOUNT not between", value1, value2, "totAmount");
            return (Criteria) this;
        }

        public Criteria andTotDegreeIsNull() {
            addCriterion("TOT_DEGREE is null");
            return (Criteria) this;
        }

        public Criteria andTotDegreeIsNotNull() {
            addCriterion("TOT_DEGREE is not null");
            return (Criteria) this;
        }

        public Criteria andTotDegreeEqualTo(String value) {
            addCriterion("TOT_DEGREE =", value, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeNotEqualTo(String value) {
            addCriterion("TOT_DEGREE <>", value, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeGreaterThan(String value) {
            addCriterion("TOT_DEGREE >", value, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeGreaterThanOrEqualTo(String value) {
            addCriterion("TOT_DEGREE >=", value, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeLessThan(String value) {
            addCriterion("TOT_DEGREE <", value, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeLessThanOrEqualTo(String value) {
            addCriterion("TOT_DEGREE <=", value, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeLike(String value) {
            addCriterion("TOT_DEGREE like", value, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeNotLike(String value) {
            addCriterion("TOT_DEGREE not like", value, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeIn(List<String> values) {
            addCriterion("TOT_DEGREE in", values, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeNotIn(List<String> values) {
            addCriterion("TOT_DEGREE not in", values, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeBetween(String value1, String value2) {
            addCriterion("TOT_DEGREE between", value1, value2, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotDegreeNotBetween(String value1, String value2) {
            addCriterion("TOT_DEGREE not between", value1, value2, "totDegree");
            return (Criteria) this;
        }

        public Criteria andTotCountIsNull() {
            addCriterion("TOT_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andTotCountIsNotNull() {
            addCriterion("TOT_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTotCountEqualTo(String value) {
            addCriterion("TOT_COUNT =", value, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountNotEqualTo(String value) {
            addCriterion("TOT_COUNT <>", value, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountGreaterThan(String value) {
            addCriterion("TOT_COUNT >", value, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountGreaterThanOrEqualTo(String value) {
            addCriterion("TOT_COUNT >=", value, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountLessThan(String value) {
            addCriterion("TOT_COUNT <", value, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountLessThanOrEqualTo(String value) {
            addCriterion("TOT_COUNT <=", value, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountLike(String value) {
            addCriterion("TOT_COUNT like", value, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountNotLike(String value) {
            addCriterion("TOT_COUNT not like", value, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountIn(List<String> values) {
            addCriterion("TOT_COUNT in", values, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountNotIn(List<String> values) {
            addCriterion("TOT_COUNT not in", values, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountBetween(String value1, String value2) {
            addCriterion("TOT_COUNT between", value1, value2, "totCount");
            return (Criteria) this;
        }

        public Criteria andTotCountNotBetween(String value1, String value2) {
            addCriterion("TOT_COUNT not between", value1, value2, "totCount");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIsNull() {
            addCriterion("SERVICE_FEE is null");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIsNotNull() {
            addCriterion("SERVICE_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andServiceFeeEqualTo(String value) {
            addCriterion("SERVICE_FEE =", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotEqualTo(String value) {
            addCriterion("SERVICE_FEE <>", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeGreaterThan(String value) {
            addCriterion("SERVICE_FEE >", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeGreaterThanOrEqualTo(String value) {
            addCriterion("SERVICE_FEE >=", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLessThan(String value) {
            addCriterion("SERVICE_FEE <", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLessThanOrEqualTo(String value) {
            addCriterion("SERVICE_FEE <=", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLike(String value) {
            addCriterion("SERVICE_FEE like", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotLike(String value) {
            addCriterion("SERVICE_FEE not like", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIn(List<String> values) {
            addCriterion("SERVICE_FEE in", values, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotIn(List<String> values) {
            addCriterion("SERVICE_FEE not in", values, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeBetween(String value1, String value2) {
            addCriterion("SERVICE_FEE between", value1, value2, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotBetween(String value1, String value2) {
            addCriterion("SERVICE_FEE not between", value1, value2, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeIsNull() {
            addCriterion("CHNL_FEE is null");
            return (Criteria) this;
        }

        public Criteria andChnlFeeIsNotNull() {
            addCriterion("CHNL_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andChnlFeeEqualTo(String value) {
            addCriterion("CHNL_FEE =", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeNotEqualTo(String value) {
            addCriterion("CHNL_FEE <>", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeGreaterThan(String value) {
            addCriterion("CHNL_FEE >", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeGreaterThanOrEqualTo(String value) {
            addCriterion("CHNL_FEE >=", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeLessThan(String value) {
            addCriterion("CHNL_FEE <", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeLessThanOrEqualTo(String value) {
            addCriterion("CHNL_FEE <=", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeLike(String value) {
            addCriterion("CHNL_FEE like", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeNotLike(String value) {
            addCriterion("CHNL_FEE not like", value, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeIn(List<String> values) {
            addCriterion("CHNL_FEE in", values, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeNotIn(List<String> values) {
            addCriterion("CHNL_FEE not in", values, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeBetween(String value1, String value2) {
            addCriterion("CHNL_FEE between", value1, value2, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andChnlFeeNotBetween(String value1, String value2) {
            addCriterion("CHNL_FEE not between", value1, value2, "chnlFee");
            return (Criteria) this;
        }

        public Criteria andFeeRateIsNull() {
            addCriterion("FEE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andFeeRateIsNotNull() {
            addCriterion("FEE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andFeeRateEqualTo(String value) {
            addCriterion("FEE_RATE =", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateNotEqualTo(String value) {
            addCriterion("FEE_RATE <>", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateGreaterThan(String value) {
            addCriterion("FEE_RATE >", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateGreaterThanOrEqualTo(String value) {
            addCriterion("FEE_RATE >=", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateLessThan(String value) {
            addCriterion("FEE_RATE <", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateLessThanOrEqualTo(String value) {
            addCriterion("FEE_RATE <=", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateLike(String value) {
            addCriterion("FEE_RATE like", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateNotLike(String value) {
            addCriterion("FEE_RATE not like", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateIn(List<String> values) {
            addCriterion("FEE_RATE in", values, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateNotIn(List<String> values) {
            addCriterion("FEE_RATE not in", values, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateBetween(String value1, String value2) {
            addCriterion("FEE_RATE between", value1, value2, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateNotBetween(String value1, String value2) {
            addCriterion("FEE_RATE not between", value1, value2, "feeRate");
            return (Criteria) this;
        }

        public Criteria andPayOrderIsNull() {
            addCriterion("PAY_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andPayOrderIsNotNull() {
            addCriterion("PAY_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andPayOrderEqualTo(String value) {
            addCriterion("PAY_ORDER =", value, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderNotEqualTo(String value) {
            addCriterion("PAY_ORDER <>", value, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderGreaterThan(String value) {
            addCriterion("PAY_ORDER >", value, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_ORDER >=", value, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderLessThan(String value) {
            addCriterion("PAY_ORDER <", value, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderLessThanOrEqualTo(String value) {
            addCriterion("PAY_ORDER <=", value, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderLike(String value) {
            addCriterion("PAY_ORDER like", value, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderNotLike(String value) {
            addCriterion("PAY_ORDER not like", value, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderIn(List<String> values) {
            addCriterion("PAY_ORDER in", values, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderNotIn(List<String> values) {
            addCriterion("PAY_ORDER not in", values, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderBetween(String value1, String value2) {
            addCriterion("PAY_ORDER between", value1, value2, "payOrder");
            return (Criteria) this;
        }

        public Criteria andPayOrderNotBetween(String value1, String value2) {
            addCriterion("PAY_ORDER not between", value1, value2, "payOrder");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeIsNull() {
            addCriterion("EXE_BEG_TIME is null");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeIsNotNull() {
            addCriterion("EXE_BEG_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeEqualTo(String value) {
            addCriterion("EXE_BEG_TIME =", value, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeNotEqualTo(String value) {
            addCriterion("EXE_BEG_TIME <>", value, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeGreaterThan(String value) {
            addCriterion("EXE_BEG_TIME >", value, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeGreaterThanOrEqualTo(String value) {
            addCriterion("EXE_BEG_TIME >=", value, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeLessThan(String value) {
            addCriterion("EXE_BEG_TIME <", value, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeLessThanOrEqualTo(String value) {
            addCriterion("EXE_BEG_TIME <=", value, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeLike(String value) {
            addCriterion("EXE_BEG_TIME like", value, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeNotLike(String value) {
            addCriterion("EXE_BEG_TIME not like", value, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeIn(List<String> values) {
            addCriterion("EXE_BEG_TIME in", values, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeNotIn(List<String> values) {
            addCriterion("EXE_BEG_TIME not in", values, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeBetween(String value1, String value2) {
            addCriterion("EXE_BEG_TIME between", value1, value2, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeBegTimeNotBetween(String value1, String value2) {
            addCriterion("EXE_BEG_TIME not between", value1, value2, "exeBegTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeIsNull() {
            addCriterion("EXE_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeIsNotNull() {
            addCriterion("EXE_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeEqualTo(String value) {
            addCriterion("EXE_END_TIME =", value, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeNotEqualTo(String value) {
            addCriterion("EXE_END_TIME <>", value, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeGreaterThan(String value) {
            addCriterion("EXE_END_TIME >", value, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("EXE_END_TIME >=", value, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeLessThan(String value) {
            addCriterion("EXE_END_TIME <", value, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeLessThanOrEqualTo(String value) {
            addCriterion("EXE_END_TIME <=", value, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeLike(String value) {
            addCriterion("EXE_END_TIME like", value, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeNotLike(String value) {
            addCriterion("EXE_END_TIME not like", value, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeIn(List<String> values) {
            addCriterion("EXE_END_TIME in", values, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeNotIn(List<String> values) {
            addCriterion("EXE_END_TIME not in", values, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeBetween(String value1, String value2) {
            addCriterion("EXE_END_TIME between", value1, value2, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExeEndTimeNotBetween(String value1, String value2) {
            addCriterion("EXE_END_TIME not between", value1, value2, "exeEndTime");
            return (Criteria) this;
        }

        public Criteria andExt1IsNull() {
            addCriterion("EXT1 is null");
            return (Criteria) this;
        }

        public Criteria andExt1IsNotNull() {
            addCriterion("EXT1 is not null");
            return (Criteria) this;
        }

        public Criteria andExt1EqualTo(String value) {
            addCriterion("EXT1 =", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotEqualTo(String value) {
            addCriterion("EXT1 <>", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1GreaterThan(String value) {
            addCriterion("EXT1 >", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1GreaterThanOrEqualTo(String value) {
            addCriterion("EXT1 >=", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1LessThan(String value) {
            addCriterion("EXT1 <", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1LessThanOrEqualTo(String value) {
            addCriterion("EXT1 <=", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1Like(String value) {
            addCriterion("EXT1 like", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotLike(String value) {
            addCriterion("EXT1 not like", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1In(List<String> values) {
            addCriterion("EXT1 in", values, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotIn(List<String> values) {
            addCriterion("EXT1 not in", values, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1Between(String value1, String value2) {
            addCriterion("EXT1 between", value1, value2, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotBetween(String value1, String value2) {
            addCriterion("EXT1 not between", value1, value2, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt2IsNull() {
            addCriterion("EXT2 is null");
            return (Criteria) this;
        }

        public Criteria andExt2IsNotNull() {
            addCriterion("EXT2 is not null");
            return (Criteria) this;
        }

        public Criteria andExt2EqualTo(String value) {
            addCriterion("EXT2 =", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotEqualTo(String value) {
            addCriterion("EXT2 <>", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2GreaterThan(String value) {
            addCriterion("EXT2 >", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2GreaterThanOrEqualTo(String value) {
            addCriterion("EXT2 >=", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2LessThan(String value) {
            addCriterion("EXT2 <", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2LessThanOrEqualTo(String value) {
            addCriterion("EXT2 <=", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2Like(String value) {
            addCriterion("EXT2 like", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotLike(String value) {
            addCriterion("EXT2 not like", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2In(List<String> values) {
            addCriterion("EXT2 in", values, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotIn(List<String> values) {
            addCriterion("EXT2 not in", values, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2Between(String value1, String value2) {
            addCriterion("EXT2 between", value1, value2, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotBetween(String value1, String value2) {
            addCriterion("EXT2 not between", value1, value2, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt3IsNull() {
            addCriterion("EXT3 is null");
            return (Criteria) this;
        }

        public Criteria andExt3IsNotNull() {
            addCriterion("EXT3 is not null");
            return (Criteria) this;
        }

        public Criteria andExt3EqualTo(String value) {
            addCriterion("EXT3 =", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotEqualTo(String value) {
            addCriterion("EXT3 <>", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3GreaterThan(String value) {
            addCriterion("EXT3 >", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3GreaterThanOrEqualTo(String value) {
            addCriterion("EXT3 >=", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3LessThan(String value) {
            addCriterion("EXT3 <", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3LessThanOrEqualTo(String value) {
            addCriterion("EXT3 <=", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3Like(String value) {
            addCriterion("EXT3 like", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotLike(String value) {
            addCriterion("EXT3 not like", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3In(List<String> values) {
            addCriterion("EXT3 in", values, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotIn(List<String> values) {
            addCriterion("EXT3 not in", values, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3Between(String value1, String value2) {
            addCriterion("EXT3 between", value1, value2, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotBetween(String value1, String value2) {
            addCriterion("EXT3 not between", value1, value2, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt4IsNull() {
            addCriterion("EXT4 is null");
            return (Criteria) this;
        }

        public Criteria andExt4IsNotNull() {
            addCriterion("EXT4 is not null");
            return (Criteria) this;
        }

        public Criteria andExt4EqualTo(String value) {
            addCriterion("EXT4 =", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotEqualTo(String value) {
            addCriterion("EXT4 <>", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4GreaterThan(String value) {
            addCriterion("EXT4 >", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4GreaterThanOrEqualTo(String value) {
            addCriterion("EXT4 >=", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4LessThan(String value) {
            addCriterion("EXT4 <", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4LessThanOrEqualTo(String value) {
            addCriterion("EXT4 <=", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4Like(String value) {
            addCriterion("EXT4 like", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotLike(String value) {
            addCriterion("EXT4 not like", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4In(List<String> values) {
            addCriterion("EXT4 in", values, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotIn(List<String> values) {
            addCriterion("EXT4 not in", values, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4Between(String value1, String value2) {
            addCriterion("EXT4 between", value1, value2, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotBetween(String value1, String value2) {
            addCriterion("EXT4 not between", value1, value2, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt5IsNull() {
            addCriterion("EXT5 is null");
            return (Criteria) this;
        }

        public Criteria andExt5IsNotNull() {
            addCriterion("EXT5 is not null");
            return (Criteria) this;
        }

        public Criteria andExt5EqualTo(String value) {
            addCriterion("EXT5 =", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotEqualTo(String value) {
            addCriterion("EXT5 <>", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5GreaterThan(String value) {
            addCriterion("EXT5 >", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5GreaterThanOrEqualTo(String value) {
            addCriterion("EXT5 >=", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5LessThan(String value) {
            addCriterion("EXT5 <", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5LessThanOrEqualTo(String value) {
            addCriterion("EXT5 <=", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5Like(String value) {
            addCriterion("EXT5 like", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotLike(String value) {
            addCriterion("EXT5 not like", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5In(List<String> values) {
            addCriterion("EXT5 in", values, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotIn(List<String> values) {
            addCriterion("EXT5 not in", values, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5Between(String value1, String value2) {
            addCriterion("EXT5 between", value1, value2, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotBetween(String value1, String value2) {
            addCriterion("EXT5 not between", value1, value2, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt6IsNull() {
            addCriterion("EXT6 is null");
            return (Criteria) this;
        }

        public Criteria andExt6IsNotNull() {
            addCriterion("EXT6 is not null");
            return (Criteria) this;
        }

        public Criteria andExt6EqualTo(String value) {
            addCriterion("EXT6 =", value, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6NotEqualTo(String value) {
            addCriterion("EXT6 <>", value, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6GreaterThan(String value) {
            addCriterion("EXT6 >", value, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6GreaterThanOrEqualTo(String value) {
            addCriterion("EXT6 >=", value, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6LessThan(String value) {
            addCriterion("EXT6 <", value, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6LessThanOrEqualTo(String value) {
            addCriterion("EXT6 <=", value, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6Like(String value) {
            addCriterion("EXT6 like", value, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6NotLike(String value) {
            addCriterion("EXT6 not like", value, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6In(List<String> values) {
            addCriterion("EXT6 in", values, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6NotIn(List<String> values) {
            addCriterion("EXT6 not in", values, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6Between(String value1, String value2) {
            addCriterion("EXT6 between", value1, value2, "ext6");
            return (Criteria) this;
        }

        public Criteria andExt6NotBetween(String value1, String value2) {
            addCriterion("EXT6 not between", value1, value2, "ext6");
            return (Criteria) this;
        }

        public Criteria andModifySourceIsNull() {
            addCriterion("MODIFY_SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andModifySourceIsNotNull() {
            addCriterion("MODIFY_SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andModifySourceEqualTo(String value) {
            addCriterion("MODIFY_SOURCE =", value, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceNotEqualTo(String value) {
            addCriterion("MODIFY_SOURCE <>", value, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceGreaterThan(String value) {
            addCriterion("MODIFY_SOURCE >", value, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_SOURCE >=", value, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceLessThan(String value) {
            addCriterion("MODIFY_SOURCE <", value, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_SOURCE <=", value, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceLike(String value) {
            addCriterion("MODIFY_SOURCE like", value, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceNotLike(String value) {
            addCriterion("MODIFY_SOURCE not like", value, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceIn(List<String> values) {
            addCriterion("MODIFY_SOURCE in", values, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceNotIn(List<String> values) {
            addCriterion("MODIFY_SOURCE not in", values, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceBetween(String value1, String value2) {
            addCriterion("MODIFY_SOURCE between", value1, value2, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifySourceNotBetween(String value1, String value2) {
            addCriterion("MODIFY_SOURCE not between", value1, value2, "modifySource");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("MODIFY_USER =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("MODIFY_USER <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("MODIFY_USER >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("MODIFY_USER <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("MODIFY_USER like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("MODIFY_USER not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("MODIFY_USER in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("MODIFY_USER not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andLockVersionIsNull() {
            addCriterion("LOCK_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andLockVersionIsNotNull() {
            addCriterion("LOCK_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andLockVersionEqualTo(String value) {
            addCriterion("LOCK_VERSION =", value, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionNotEqualTo(String value) {
            addCriterion("LOCK_VERSION <>", value, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionGreaterThan(String value) {
            addCriterion("LOCK_VERSION >", value, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionGreaterThanOrEqualTo(String value) {
            addCriterion("LOCK_VERSION >=", value, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionLessThan(String value) {
            addCriterion("LOCK_VERSION <", value, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionLessThanOrEqualTo(String value) {
            addCriterion("LOCK_VERSION <=", value, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionLike(String value) {
            addCriterion("LOCK_VERSION like", value, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionNotLike(String value) {
            addCriterion("LOCK_VERSION not like", value, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionIn(List<String> values) {
            addCriterion("LOCK_VERSION in", values, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionNotIn(List<String> values) {
            addCriterion("LOCK_VERSION not in", values, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionBetween(String value1, String value2) {
            addCriterion("LOCK_VERSION between", value1, value2, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andLockVersionNotBetween(String value1, String value2) {
            addCriterion("LOCK_VERSION not between", value1, value2, "lockVersion");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("UPDATE_TIME like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("UPDATE_TIME not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WZ_EXE_ORDER
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}