package com.company.core.entity;

public class WZExeOrderDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.ORDER_ID
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.TOT_AMOUNT
     *
     * @mbg.generated
     */
    private String totAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.TOT_DEGREE
     *
     * @mbg.generated
     */
    private String totDegree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.TOT_COUNT
     *
     * @mbg.generated
     */
    private String totCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.SERVICE_FEE
     *
     * @mbg.generated
     */
    private String serviceFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.CHNL_FEE
     *
     * @mbg.generated
     */
    private String chnlFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.FEE_RATE
     *
     * @mbg.generated
     */
    private String feeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.PAY_ORDER
     *
     * @mbg.generated
     */
    private String payOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.EXE_BEG_TIME
     *
     * @mbg.generated
     */
    private String exeBegTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.EXE_END_TIME
     *
     * @mbg.generated
     */
    private String exeEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.EXT1
     *
     * @mbg.generated
     */
    private String ext1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.EXT2
     *
     * @mbg.generated
     */
    private String ext2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.EXT3
     *
     * @mbg.generated
     */
    private String ext3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.EXT4
     *
     * @mbg.generated
     */
    private String ext4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.EXT5
     *
     * @mbg.generated
     */
    private String ext5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.EXT6
     *
     * @mbg.generated
     */
    private String ext6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.MODIFY_SOURCE
     *
     * @mbg.generated
     */
    private String modifySource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.MODIFY_USER
     *
     * @mbg.generated
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.LOCK_VERSION
     *
     * @mbg.generated
     */
    private String lockVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WZ_EXE_ORDER.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.ID
     *
     * @return the value of WZ_EXE_ORDER.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.ID
     *
     * @param id the value for WZ_EXE_ORDER.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.ORDER_ID
     *
     * @return the value of WZ_EXE_ORDER.ORDER_ID
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.ORDER_ID
     *
     * @param orderId the value for WZ_EXE_ORDER.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.USER_ID
     *
     * @return the value of WZ_EXE_ORDER.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.USER_ID
     *
     * @param userId the value for WZ_EXE_ORDER.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.STATUS
     *
     * @return the value of WZ_EXE_ORDER.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.STATUS
     *
     * @param status the value for WZ_EXE_ORDER.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.TOT_AMOUNT
     *
     * @return the value of WZ_EXE_ORDER.TOT_AMOUNT
     *
     * @mbg.generated
     */
    public String getTotAmount() {
        return totAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.TOT_AMOUNT
     *
     * @param totAmount the value for WZ_EXE_ORDER.TOT_AMOUNT
     *
     * @mbg.generated
     */
    public void setTotAmount(String totAmount) {
        this.totAmount = totAmount == null ? null : totAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.TOT_DEGREE
     *
     * @return the value of WZ_EXE_ORDER.TOT_DEGREE
     *
     * @mbg.generated
     */
    public String getTotDegree() {
        return totDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.TOT_DEGREE
     *
     * @param totDegree the value for WZ_EXE_ORDER.TOT_DEGREE
     *
     * @mbg.generated
     */
    public void setTotDegree(String totDegree) {
        this.totDegree = totDegree == null ? null : totDegree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.TOT_COUNT
     *
     * @return the value of WZ_EXE_ORDER.TOT_COUNT
     *
     * @mbg.generated
     */
    public String getTotCount() {
        return totCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.TOT_COUNT
     *
     * @param totCount the value for WZ_EXE_ORDER.TOT_COUNT
     *
     * @mbg.generated
     */
    public void setTotCount(String totCount) {
        this.totCount = totCount == null ? null : totCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.SERVICE_FEE
     *
     * @return the value of WZ_EXE_ORDER.SERVICE_FEE
     *
     * @mbg.generated
     */
    public String getServiceFee() {
        return serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.SERVICE_FEE
     *
     * @param serviceFee the value for WZ_EXE_ORDER.SERVICE_FEE
     *
     * @mbg.generated
     */
    public void setServiceFee(String serviceFee) {
        this.serviceFee = serviceFee == null ? null : serviceFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.CHNL_FEE
     *
     * @return the value of WZ_EXE_ORDER.CHNL_FEE
     *
     * @mbg.generated
     */
    public String getChnlFee() {
        return chnlFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.CHNL_FEE
     *
     * @param chnlFee the value for WZ_EXE_ORDER.CHNL_FEE
     *
     * @mbg.generated
     */
    public void setChnlFee(String chnlFee) {
        this.chnlFee = chnlFee == null ? null : chnlFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.FEE_RATE
     *
     * @return the value of WZ_EXE_ORDER.FEE_RATE
     *
     * @mbg.generated
     */
    public String getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.FEE_RATE
     *
     * @param feeRate the value for WZ_EXE_ORDER.FEE_RATE
     *
     * @mbg.generated
     */
    public void setFeeRate(String feeRate) {
        this.feeRate = feeRate == null ? null : feeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.PAY_ORDER
     *
     * @return the value of WZ_EXE_ORDER.PAY_ORDER
     *
     * @mbg.generated
     */
    public String getPayOrder() {
        return payOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.PAY_ORDER
     *
     * @param payOrder the value for WZ_EXE_ORDER.PAY_ORDER
     *
     * @mbg.generated
     */
    public void setPayOrder(String payOrder) {
        this.payOrder = payOrder == null ? null : payOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.EXE_BEG_TIME
     *
     * @return the value of WZ_EXE_ORDER.EXE_BEG_TIME
     *
     * @mbg.generated
     */
    public String getExeBegTime() {
        return exeBegTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.EXE_BEG_TIME
     *
     * @param exeBegTime the value for WZ_EXE_ORDER.EXE_BEG_TIME
     *
     * @mbg.generated
     */
    public void setExeBegTime(String exeBegTime) {
        this.exeBegTime = exeBegTime == null ? null : exeBegTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.EXE_END_TIME
     *
     * @return the value of WZ_EXE_ORDER.EXE_END_TIME
     *
     * @mbg.generated
     */
    public String getExeEndTime() {
        return exeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.EXE_END_TIME
     *
     * @param exeEndTime the value for WZ_EXE_ORDER.EXE_END_TIME
     *
     * @mbg.generated
     */
    public void setExeEndTime(String exeEndTime) {
        this.exeEndTime = exeEndTime == null ? null : exeEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.EXT1
     *
     * @return the value of WZ_EXE_ORDER.EXT1
     *
     * @mbg.generated
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.EXT1
     *
     * @param ext1 the value for WZ_EXE_ORDER.EXT1
     *
     * @mbg.generated
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.EXT2
     *
     * @return the value of WZ_EXE_ORDER.EXT2
     *
     * @mbg.generated
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.EXT2
     *
     * @param ext2 the value for WZ_EXE_ORDER.EXT2
     *
     * @mbg.generated
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.EXT3
     *
     * @return the value of WZ_EXE_ORDER.EXT3
     *
     * @mbg.generated
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.EXT3
     *
     * @param ext3 the value for WZ_EXE_ORDER.EXT3
     *
     * @mbg.generated
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.EXT4
     *
     * @return the value of WZ_EXE_ORDER.EXT4
     *
     * @mbg.generated
     */
    public String getExt4() {
        return ext4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.EXT4
     *
     * @param ext4 the value for WZ_EXE_ORDER.EXT4
     *
     * @mbg.generated
     */
    public void setExt4(String ext4) {
        this.ext4 = ext4 == null ? null : ext4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.EXT5
     *
     * @return the value of WZ_EXE_ORDER.EXT5
     *
     * @mbg.generated
     */
    public String getExt5() {
        return ext5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.EXT5
     *
     * @param ext5 the value for WZ_EXE_ORDER.EXT5
     *
     * @mbg.generated
     */
    public void setExt5(String ext5) {
        this.ext5 = ext5 == null ? null : ext5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.EXT6
     *
     * @return the value of WZ_EXE_ORDER.EXT6
     *
     * @mbg.generated
     */
    public String getExt6() {
        return ext6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.EXT6
     *
     * @param ext6 the value for WZ_EXE_ORDER.EXT6
     *
     * @mbg.generated
     */
    public void setExt6(String ext6) {
        this.ext6 = ext6 == null ? null : ext6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.MODIFY_SOURCE
     *
     * @return the value of WZ_EXE_ORDER.MODIFY_SOURCE
     *
     * @mbg.generated
     */
    public String getModifySource() {
        return modifySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.MODIFY_SOURCE
     *
     * @param modifySource the value for WZ_EXE_ORDER.MODIFY_SOURCE
     *
     * @mbg.generated
     */
    public void setModifySource(String modifySource) {
        this.modifySource = modifySource == null ? null : modifySource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.MODIFY_USER
     *
     * @return the value of WZ_EXE_ORDER.MODIFY_USER
     *
     * @mbg.generated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.MODIFY_USER
     *
     * @param modifyUser the value for WZ_EXE_ORDER.MODIFY_USER
     *
     * @mbg.generated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.LOCK_VERSION
     *
     * @return the value of WZ_EXE_ORDER.LOCK_VERSION
     *
     * @mbg.generated
     */
    public String getLockVersion() {
        return lockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.LOCK_VERSION
     *
     * @param lockVersion the value for WZ_EXE_ORDER.LOCK_VERSION
     *
     * @mbg.generated
     */
    public void setLockVersion(String lockVersion) {
        this.lockVersion = lockVersion == null ? null : lockVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.CREATE_TIME
     *
     * @return the value of WZ_EXE_ORDER.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.CREATE_TIME
     *
     * @param createTime the value for WZ_EXE_ORDER.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WZ_EXE_ORDER.UPDATE_TIME
     *
     * @return the value of WZ_EXE_ORDER.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WZ_EXE_ORDER.UPDATE_TIME
     *
     * @param updateTime the value for WZ_EXE_ORDER.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}